### ISSUE TITLE
Add better documentation for .jsx file users

### ISSUE THREAD

**Issue by jfarid27** [AtomLinter/linter-eslint#1046]
## Issue Type
"Feature Request"

## Issue Description
Add better documentation for users that are looking to lint .jsx files. It appears one needs to have the `language-javascript-jsx` package installed to recognize the .jsx scope, but the documentation doesn't mention this.

## Bug Checklist
I followed some of the guidelines [here](https://github.com/AtomLinter/linter-eslint/issues/834), but I decided to look into the Cursor Scopes for a .jsx file. Low and behold, after installing linter-eslint, the cursor scope was text-plain.null, so the application of linter-eslint wasn't working.

## Other Stuff
- I'd recommend making this package a dependency, but that's not my call
- [PR 1047](https://github.com/AtomLinter/linter-eslint/pull/1047)

## Program Details
Ubuntu 16.04
Atom 1.20.0

**Comment by Arcanemagus** [comment]
> Low and behold, after installing linter-eslint, the cursor scope was text-plain.null

`linter-eslint` has _nothing_ to do with getting Atom to recognize a file, it only starts interacting after this step has taken place.

**Comment by jfarid27** [comment]
@Arcanemagus do you think a PR is necessary then? Honestly, just having the issue in public is a great first step as a signal to people that they may not have the correct Atom scopes installed to recognize .jsx. I figured it's not really an "issue" but more of a "dependency".

**Comment by Arcanemagus** [comment]
I personally consider support for anything other than Javascript to be an advanced feature, especially since you need to customize ESLint with a new parser to get things working. It wouldn't _hurt_ to have some documentation out there for it though. Documentation is one area this package could use a lot of help in, especially for new users since it's rather hard to know what's confusing about it currently after writing the code for years 😉.

> just having the issue in public is a great first step

This is definitely _not_ the first issue relating to how to set up JSX (or other custom syntaxes) 😛.
