### ISSUE TITLE
Toggling Fix errors on save from command palette 

### ISSUE THREAD

**Issue by ewanharris** [AtomLinter/linter-eslint#1049]
## Issue Type
Feature Request/Question

## Issue Description
I tend to use linter-eslint with `Fix errors on save` enabled, however since the config I use has a warning for `debugger;` statements when attempting to debug I lose those. Is there a way to toggle this setting from the command palette rather than going to the setting manually?

## Other stuff

- I took a search through the repo and couldn't find any references to this in prior issues/the code. Sorry if this is a dupe!
- Happy to help where I can if this is a valid feature request that the team likes :)

**Comment by IanVS** [comment]
Hi @ewanharris.  I use `Fix errors on save` as well, and there have been a few times where I did not want it to "fix" my code, particularly when I'm debugging.  That's why we've added the option to `Disable specific rules from fixes`.  I'd recommend adding the `no-debugger` rule there.  Then, you won't have to deal with turning the option off and on, but you'll still see that it's a linting error.  Would that meet your needs?

**Comment by skylize** [comment]
This is an upstream issue. I've passed on your request to `linter-ui-default`, which is the package this setting belongs to. Follow that Issue for any further progress. [`linter-ui-default` #500](https://github.com/steelbrain/linter-ui-default/issues/500)

Closing as won't fix.

**Comment by skylize** [comment]
Hmm. Wait a minute. I'm brain-farting here. We do control that setting. :d But 

But I think this is still "won't fix", as we have already other settings to work around this.
