### ISSUE TITLE
Error with eslint-import-resolver-babel-module

### ISSUE THREAD

**Issue by ernieyang09** [AtomLinter/linter-eslint#1080]
## Issue Type

Bug

## Issue Description

no problem in VScode, eslint cli, fast eslint(another atom package)

![error](https://user-images.githubusercontent.com/6268302/35029984-62382586-fb98-11e7-9a6d-e18a851ebe8b.png)

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.23.3
linter-eslint version: 8.4.0
ESLint version: 4.15.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/ernieyang09/Desktop/xx/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "punctuation.terminator.statement.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
@ernieyang09 If we are going to have any hope of reproducing this to see where the bug is you'll need to either attach a `.zip` of a minimal reproduction case, create a gist, or the best option: Create a minimal repository.

**Comment by ernieyang09** [comment]
yap,
just try to create a [repo](https://github.com/ernieyang09/babel_module_plugin_test) and luckily reproduce the problem.

first commit is no error.
After I add babel-preset-babili, atom can't work properly.

thx

**Comment by Arcanemagus** [comment]
`eslint-plugin-import` silences _all_ errors coming from import resolvers. It's a bug I've brought up with them several times before and they seem to have no interest in fixing.

In this case `eslint-import-resolver-babel-module` is throwing an error that simply says:
![image](https://user-images.githubusercontent.com/427137/35167702-51aff13e-fd0b-11e7-86bd-31f9789eb038.png)

That leads to https://github.com/tleunen/eslint-import-resolver-babel-module/pull/34, which it [looks like](https://github.com/tleunen/eslint-import-resolver-babel-module/pull/34/files#diff-1fdf421c05c1140f6d71444ea2b27638R30) is throwing the error when trying to load your configuration.

After digging _deep_ into the `babel-core` `OptionManager`, I managed to get this error out of it:
```
ReferenceError(Unknown plugin "transform-runtime" specified in "<path>\\babel_module_plugin_test\\.babelrc.env.production" at 0, attempted to resolve relative to "<path>")
```

I'm actually not sure why the above screenshot is showing an empty Error object as it _should_ be that error, but in any case the problem is that in your [production environment configuration](https://github.com/ernieyang09/babel_module_plugin_test/blob/2d7db7878b676ff90ae4dc44a97a9167723a5b12/.babelrc#L20) you have `transform-runtime` defined as a plugin but don't actually have that plugin anywhere in your project.

**Comment by skylize** [comment]
Assuming the above tracing by @Arcanemagus is correct 🤞 (nice source code digging bro 😸 ) , here is what you need to know. https://babeljs.io/docs/plugins/transform-runtime/

**Comment by SchlagerKhan** [comment]
One year later..

I'm getting the same error with `{ code: "MODULE_NOT_FOUND" }` . But I don't have any babel `transform-runtime` in my project. What did you actually end up doing to fix this?

**Comment by Arcanemagus** [comment]
It's not a bug in `linter-eslint`, so there is nothing to "fix" here @SchlagerKhan.

Since the little bit that you have shared so far has nothing to do with the error originally reported here I'm not surprised you don't have `transform-runtime` in your project. If you would like us to take a look at it please create a repository you can share with us that reproduces the problem (like was done [here](https://github.com/AtomLinter/linter-eslint/issues/1080#issuecomment-358245417)) and create a _new_ issue.
