### ISSUE TITLE
Restart IDE to get linting

### ISSUE THREAD

**Issue by Cesarcs7** [AtomLinter/linter-eslint#1113]
## Issue Type
Question

## Issue Description
Hi, linter-eslint wont work unless i restart the IDE every time i want to check for errors, i also dont know how to make a Debug output, the command doesnt seems to work at all. Please if anyone could help me or suggest something it would be nice. Im very noob at it, dont understand the whole CLI stuff just yet

Thanks.

## Bug Checklist
- [ ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```

**Comment by skylize** [comment]
> i also dont know how to make a Debug output

You can run the `Linter ESlint: Debug` from the Command Palette inside Atom. Press <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>P</kbd> (Linux/Windows) or <kbd>⌘</kbd>-<kbd>Shift</kbd>-<kbd>P</kbd> (Mac) to open the Command Palette and type `eslint debug` and hit <kbd>Enter</kbd>. You should get a popup message in Atom with a bunch of miscellaneous info about the settings we've interpreted from your system. Copy-paste that here.

Please also open a terminal and go to the root folder of your project, `cd /path/to/project/root`. Then just run ESLint from that directory. 
* If you have it installed globally (`npm install --global eslint` from anywhere), then you can just type `eslint` from the project root. 
* If you have it installed locally to your project (`npm install eslint` from your project folder), you can type `npx eslint` to run the local binary. 
* If you have not installed `eslint` at all, you should do that. Using the built-in copy of `eslint` that comes pre-installed with `linter-eslint` is very problematic, almost never works the way you would want it to, and is planned for deprecation.

> linter-eslint wont work unless i restart the IDE

This might be an `atom-ide-ui` problem rather than a `linter-eslint` problem. Please try using [`linter-ui-default`](https://atom.io/packages/linter-ui-default) to find out if you have the same issues as you do when using IDE.

**Comment by Cesarcs7** [comment]
Thanks for your answer.

# Debug:

every time i tried to run this command an error saying"Typeerror Path must be a string. Received undefined" appeared, after several intents it worked.

Atom version: 1.24.0
linter-eslint version: 8.4.1
ESLint version: 4.18.1
Hours since last Atom restart: 0
Platform: win32
Using bundled fallback ESLint from: C:\Users\Cesar\.atom\packages\linter-eslint\node_modules\eslint
Current file's scopes: [
  "source.js",
  "meta.brace.curly.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}

Debug Eslint****

E:\EslintTest\node_modules\eslint\bin\eslint.js
eslint [options] file.js [file.js] [dir]

Basic configuration:
  --no-eslintrc                  Disable use of configuration from .eslintrc.*
  -c, --config path::String      Use this configuration, overriding .eslintrc.* config
                                 options if present
  --env [String]                 Specify environments
  --ext [String]                 Specify JavaScript file extensions - default: .js
  --global [String]              Define global variables
  --parser String                Specify the parser to be used
  --parser-options Object        Specify parser options

Specifying rules and plugins:
  --rulesdir [path::String]      Use additional rules from this directory
  --plugin [String]              Specify plugins
  --rule Object                  Specify rules

Fixing problems:
  --fix                          Automatically fix problems
  --fix-dry-run                  Automatically fix problems without saving the changes to
                                 the file system

Ignoring files:
  --ignore-path path::String     Specify path of ignore file
  --no-ignore                    Disable use of ignore files and patterns
  --ignore-pattern [String]      Pattern of files to ignore (in addition to those in
                                 .eslintignore)

Using stdin:
  --stdin                        Lint code provided on <STDIN> - default: false
  --stdin-filename String        Specify filename to process STDIN as

Handling warnings:
  --quiet                        Report errors only - default: false
  --max-warnings Int             Number of warnings to trigger nonzero exit code - default:
                                 -1

Output:
  -o, --output-file path::String  Specify file to write report to
  -f, --format String            Use a specific output format - default: stylish
  --color, --no-color            Force enabling/disabling of color

Inline configuration comments:
  --no-inline-config             Prevent comments from changing config or rules
  --report-unused-disable-directives  Adds reported errors for unused eslint-disable
                                      directives

Caching:
  --cache                        Only check changed files - default: false
  --cache-file path::String      Path to the cache file. Deprecated: use --cache-location -
                                 default: .eslintcache
  --cache-location path::String  Path to the cache file or directory

Miscellaneous:
  --init                         Run config initialization wizard - default: false
  --debug                        Output debugging information
  -h, --help                     Show help
  -v, --version                  Output the version number
  --print-config path::String    Print the configuration for the given file



Eslint seems to work perfectly, i tried with a couple of files and it was no problem. Just linter-eslint is the one who is doing nothing until i reset the IDE, i also have linter-ui-deault installed, wich was installed as a dependency from linter-eslint and linter.

**Comment by noe132** [comment]
@Cesarcs7 Hey! I have the same issue. As I know that you don't have to restart Atom to get eslint working, just open settings -> packages, disable linter-eslint and re-enable it it'll work.

I have many project opend in the sidebar and each of them have individual eslint config file. I have to open different files from different projects using different eslintrc rules file to lint code open in atom while I coding. Usually after a while doing my job then there is no lint message from linter-eslint anymore, but eslint cli gives the proper lint result. Until I re-enable linter-eslist or restart atom like @Cesarcs7 said that linter-eslint shows the lint result.

I have a feeling that maybe it's related about while linting files in different project using different eslintrc file, there could be something wrong with finding correct eslintrc file to use? I can't be sure about this, cause I don't know how to show that what current using eslintrc file is, it's not displayed in linter-eslint debug info. sometimes when I try using "Linter eslint: debug" in a project without eslint or eslintrc, I got message "TypeError: Path must be a string. Received undefined", I don't know if this is helpful finding the problem.

It's hard to give a minimium case to reproduce this issue, because it's kinda happen randomly.

**Comment by skylize** [comment]
@Cesarcs7 Does @noe132's issue sound similar to yours? Are you able to lint for a while before you need to restart IDE?

I see that `linter-eslint` is using the bundled-falback copy of `eslint`.
```
Using bundled fallback ESLint from: C:\Users\Cesar\.atom\packages\linter-eslint\node_modules\eslint
```
That means we failed to locate the root of your project. Does your project have a config file? one of `.eslintrc.json`, `.eslintrc.js`, `.eslintrc.yaml` or entry of `eslintConfig` in `package.json`?

**Comment by skylize** [comment]
@noe132 I'm wondering if you might be dealing with an edge case for the caching system. We do some caching of config file paths and `eslint` binary paths. So if you are moving files around a lot, and in particular if you move the config while Atom is running, you may find `linter-eslint` trying to use a stale path.

Currently we have no way to invalidate the cache. I've been brainstorming how that might be done without the cost being too high, but don't have any great solutions yet. You could disable the cache altogether from Settings, but this would be extremely hard on your disk drive and likely cause performance problems.

**Comment by Cesarcs7** [comment]
@skylize 
I made an update to  linter-ui-default, install everything again in a new project and it seems to work really well. Even with create-react-app, i also enabled and dissabled linter-eslint, it didnt worked before but after the  linter-ui-defaults update every strated to work as it should.
 thanks for the help, i will be testing it for now and let you know if something comes up.

**Comment by Cesarcs7** [comment]
Linter-eslint stops working again it seems that the linter-ui-default problem was not the root of the problem, i figured out that if i unchecked _"Disable when no Eslint config file is found"_ it starts working again but throws an error: **Error while running Eslint, no such file or directory, uv_chdir.**

In my eslintrc.js file is just this:

`module.exports = {
    "extends": "airbnb"
};
`
and more config giles in my node_modules directory.

when i restart Atom i can see the errors, but as soon as i press any key in the code, all highlighting dissappear. And i have to restart it again. Enabling und disabling the packages doesnt seems to work neither.

**Comment by IanVS** [comment]
@Cesarcs7 is there a reason you need to use the bundled fallback, rather than adding eslint and the necessary plugins (`eslint-config-airbnb` along with its peer dependencies) into your project?

**Comment by Cesarcs7** [comment]
I think i resolved the problem, i was using Atom to deal with files inside an USB drive. Every time i tried to use linter-eslint there it wouldnt work. but using local files in my directory worked in both my PC and laptop perfectly. I looked at my debug file and there was no bundled fallback anymore(i dont even know what that is :D), sorry for the missunderstandig, and thanks for your help. 

i guess  linter-eslint couldnt get the files while beeing in the USB drive directory...
