### ISSUE TITLE
Request to use bin path in package.json for eslint binary

### ISSUE THREAD

**Issue by rxgx** [AtomLinter/linter-eslint#1133]
## Issue Type
Feature Request

## Issue Description

I have created a ESLint [config bundle](https://github.com/GratefulVentures/javascript/tree/master/packages) module to package all the dependencies for a ESLint sharable configuration. This works great for `npm run lint` or `npx eslint`. The one issue I have is that my bundle requires `eslint` to be run from the `bin` property in the bundle's `package.json`. Is there a way to get Atom to detect and use the `bin` path?

### Bundle package.json

```json
{
  "bin": {
    "eslint": "node_modules/eslint/bin/eslint.js"
  },
  "dependencies": {
    "@grateful/eslint-config-node": "^1.1.0",
    "eslint": "^4.19.1",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-prettier": "^2.6.0",
    "prettier": "^1.11.1"
  },
  "bundleDependencies": [
    "@grateful/eslint-config-node",
    "eslint",
    "eslint-config-prettier",
    "eslint-plugin-prettier",
    "prettier"
  ]
}
```

**Comment by Arcanemagus** [comment]
I'm closing this as `wontfix` since this isn't something we are going to support.

Specifying the `bin` property like that is claiming that you _are_ `eslint`, which is clearly incorrect since essentially you are just making your own version of `standard` and still calling it `eslint`.

The proper way to share configurations is to create a shared configuration, and set the required `eslint` as a `peerDependency`. Bundling things up like that is just abusing a quirk of how your packages are installed.

If you want an example of the right way to publish a shared ESLint configuration check out [`eslint-config-airbnb-base`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base), or any of the other configurations out there.
