### ISSUE TITLE
Global Linter Should Be Fallback

### ISSUE THREAD

**Issue by bcnichols3** [AtomLinter/linter-eslint#1142]
## Issue Type
Feature Request

## Issue Description
Some projects I work on have a local eslint, as is recommended by the community, and I of course want to obey it. Many other projects do not have a local eslint. I always prefer to have at least a basic, stripped down linter running to catch mis-typings immediately. I feel like this isn't an unusual position to be in. As it stands, I have to manually turn global eslint off and on depending on the project because linter-eslint prioritizes global over local, for some reason. In my mind, this should be the reverse -- or at least we should have an option of which linter (global or local) has priority.

**Comment by IanVS** [comment]
Yep, I totally agree!  This has been discussed a bit in https://github.com/AtomLinter/linter-eslint/issues/845, we're just looking for someone to help out with a PR.  I expect to have a little extra time for OSS work soon, and might be able to get to it.  But, if you'd like to take a crack at a PR, that would be awesome.

For now, I'm going to close this since we already have #845 to track it.  Thanks for the prod!
