### ISSUE TITLE
linter not discovering variable redeclaration inside if statement while using let keyword

### ISSUE THREAD

**Issue by rohanrichards** [AtomLinter/linter-eslint#1164]
## Issue Type
Bug

## Issue Description
Linting with Atom fails to discover when a variable has already been declared, specifically: within an if statement, when using the let keyword. Linter-eslint incorrectly treats the if statement as a new scope.

```
let foo = 'bar';

if(foo){
	console.log(foo); //js hoists the declaration to here and foo is undefined causing a crash
	let foo = undefined; //linter does not discover this as a fatal error
}

let foo = 'foobar'; //correctly reports this as a fatal error
```
N.B when using `var` the linter works as expected
I actually think this may be an issue with eslint, I'll leave this issue float here for a bit to see if some smarter people can confirm this for me before moving it over to their issue tracker.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below
//not sure where to run the above command!

```
Linter Eslint: Debug output here
```

**Comment by skylize** [comment]
Good find ... er, I mean *bad* find? This is not limited to `if` statements, fails with any block.

Please report upstream https://github.com/eslint/eslint .

In the meantime, if you enable [`no-shadow`](https://eslint.org/docs/rules/no-shadow), then this type of error cannot go unnoticed. 

When I first discovered the `no-shadow` rule, I thought it was annoying. But since then I realized that shadowing variables within the same file is almost always unnecessarily confusing. So this rule will probably turn out to be helpful for you regardless. You can always disable it inline for special circumstances.
