### ISSUE TITLE
Not using .eslintrc anymore after update

### ISSUE THREAD

**Issue by fa7ad** [AtomLinter/linter-eslint#118]
So, I just updated the plugin and `linter` plugin as well. after I did that the linter seems to completely ignore my eslintrc configurations and highlight all the meteor code in red

**Comment by iam4x** [comment]
@fa7ad Where is your `.eslintrc` ? Do you have eslint installed to your project?

**Comment by fa7ad** [comment]
I don't have eslint in my project (since this is a meteor app)
and `.eslintrc` is in the root directory

I just reverted back to 0.5.10 and it seems to work again

**Comment by wouldgo** [comment]
Hi,
I've the same behavior of @fa7ad. Also in my scenario I've the `.eslintrc` file in the project root direcotry and I do have installed eslint as dev dependency in my project (I'm using also in a precommit hook).

**Comment by jokeyrhyme** [comment]
Same here. Atom 0.211.0, linter-eslint 1.0.2.
My project has a .eslintrc, eslint is in devDependencies, and `$(npm bin)/eslint .` returns nothing.
I am using "extends" in my .eslintrc, but I remember this working at least recently: https://github.com/blinkmobile/jqpromise.js/blob/master/.eslintrc

**Comment by iam4x** [comment]
Do you any logs into console: `CMD-ALT-I` ?

**Comment by jokeyrhyme** [comment]
@iam4x nope. I see errors from the go-plus package because it can't find a valid `go`, but there aren't any error messages from linter or linter-eslint.

Hey, that's weird... It's just JavaScript files in the project root (next to .eslintrc) that are acting as though they have no .eslintrc, e.g. /index.js and /karma.conf.js 
/test/index.js is linting just fine. Deliberate errors are showing up, otherwise I get a pass.

Perhaps linter-eslint is treating files that are siblings of the .eslintrc file differently?

**Comment by iam4x** [comment]
@jokeyrhyme I'm checking out your repo. Can you give me your atom configuration for linter-eslint and linter? Like are you using rulesDir?

**Comment by iam4x** [comment]
@johanbrook Okey I can reproduce thank's for investigation help :)

**Comment by iam4x** [comment]
New version published, can you confirm it does fixes the issue for you?

**Comment by jokeyrhyme** [comment]
Everything looks fine in linter-eslint 1.0.6. :) <3 Thanks!

**Comment by wouldgo** [comment]
Hi all,
As soon as I could test again I'll update here.

Thanks for commitment!
Dario

**Comment by fa7ad** [comment]
Working for me as well :+1:

**Comment by wouldgo** [comment]
it works also here.
Thanks.
