### ISSUE TITLE
Nested package.json causing eslint to not read root package.json dependencies

### ISSUE THREAD

**Issue by eurobob** [AtomLinter/linter-eslint#1287]
## Issue Type
Bug

### Motivation:
I'm setting up a new project and trying a new component structure. The `Atoms.js` file contains styled components, and since using index.js is not so useful for debugging, I want to name entry files accordingly. To do this I am using a component-scoped package.json to set "main".

Project root:
```
my-project
├── package.json
└─┬ src
  └─┬ components
    └─┬ Footer
      ├── Footer.js
      ├── Atoms.js
      └── package.json
```
src/components/Footer/package.json:
```
{
  "main": "Footer.js"
}
```

### Problem
While the CLI has no problem with this, eslint in Atom is unable to resolve dependencies and absolute imports configured in the root package.json

I had a look at some other issues, and it appears that nested `.eslintrc` functionality is taken care of, but it seems as though parent `package.json` configurations aren't been adhered to.

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.38.2
linter-eslint version: 8.5.5
ESLint version: 5.16.0
Hours since last Atom restart: 0.7
Platform: darwin
Using local project ESLint from: /Users/rob/web/projects/simplipleasure/new/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function.js",
  "meta.tag.jsx",
  "JSXAttrs",
  "JSXNested",
  "meta.tag.jsx",
  "JSXAttrs",
  "JSXNested",
  "meta.tag.jsx",
  "JSXAttrs",
  "JSXNested",
  "meta.tag.jsx",
  "JSXAttrs",
  "JSXNested",
  "meta.tag.jsx",
  "JSXAttrs",
  "JSXNested",
  "meta.tag.jsx",
  "punctuation.definition.tag.jsx"
]
linter-eslint configuration: {
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}
```

**Comment by Arcanemagus** [comment]
> but it seems as though parent package.json configurations aren't been adhered to.

That's because there is no such thing. `package.json` is considered the root of the project.

Can you share a zip or a repository of an example project, and the _exact_ commands you are running to test in the CLI, as well as where you are running them? I suspect you aren't running ESLint from the CLI the way you should be to test this.

**Comment by IanVS** [comment]
@eurobob, where are you setting your eslint configuration?  Do you have an `eslintConfig` key in your top-level `package.json`?

**Comment by IanVS** [comment]
Hmm, I took a look, and it seems like linter-eslint is operating correctly.  I cloned the repo (thanks for providing it!), did a `yarn install`, ran `yarn eslint .`, and got the following errors from `Footer.js`:

```
  1:1   error  'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it  import/no-extraneous-dependencies
  2:23  error  Unable to resolve path to module 'components/Container'                                 import/no-unresolved
```

When I open the file in atom, I see those same errors:

![image](https://user-images.githubusercontent.com/4616705/60690847-c347f000-9e98-11e9-985d-0aeefec6dfeb.png)

So, I think this has more to do with the way you are trying to use `package.json` files instead of `index.js` files, and how that interacts with `eslint-plugin-import`.

**Comment by eurobob** [comment]
Yep. I ended up using https://www.npmjs.com/package/directory-named-webpack-plugin instead to achieve my desired functionality.

Thanks for taking a look
