### ISSUE TITLE
Please update to latest eslint (~6.2.2)

### ISSUE THREAD

**Issue by mercmobily** [AtomLinter/linter-eslint#1303]
## Issue Description

ESLint finally has [dynamic imports](https://github.com/eslint/eslint/issues/11803). At the moment, linter-eslint has as dependency an old version of eslint:

    "eslint": "4.19.1",

Please upgrade to `~6.2.2` so that we get dynamic imports.

The goal is to suppress:

	Parsing error: 'import' and 'export' may only appear at the top level (Fatal)

**Comment by Arcanemagus** [comment]
The version embedded here should have _nothing_ to do with the version used to lint your project. You should install a current version locally in your project and this package will automatically use that to lint your code.

**Comment by mercmobily** [comment]
True. But... Why don't you update it anyway?

**Comment by Arcanemagus** [comment]
https://github.com/AtomLinter/linter-eslint/pull/1277 is tracking updating it here, there's no rush especially since we plan on entirely removing the bundled version so people aren't encouraged to use it (this issue being a prime example of why that's a problem).

Since upgrading the bundled version is already being tracked elsewhere I'm going to close this issue, thanks for taking the time to file an issue though!

**Comment by mercmobily** [comment]
I realised that the preferred way is the project's eslint afterwards --
sorry.
I totally agree on removing eslint as a dependency, unless there is
something you are actually using from there
