### ISSUE TITLE
Unable to Verify Leaf

### ISSUE THREAD

**Issue by BryantIT** [AtomLinter/linter-eslint#1329]
## Issue Type
Bug

## Issue Description
Installing failed.

## Bug Checklist
- [ ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://codeload.github.com/AtomLinter/linter-eslint/legacy.tar.gz/v8.5.5 failed, reason: unable to verify the first certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ninjalikereflex/.atom/.apm/_logs/2020-02-04T03_05_22_190Z-debug.log

**Comment by Arcanemagus** [comment]
It looks like your system can't validate the certificate for `codeload.github.com`? You'll want to make sure your OS is updated.

Closing this as this is an issue installing the package that we have no control over (and since I'm an Atom maintainer as well I'll tell you that this isn't something that can be fixed there either... this is an issue with your local system, or somebody is trying to MITM you!).
