### ISSUE TITLE
Support for ESLint 8

### ISSUE THREAD

**Issue by EvHaus** [AtomLinter/linter-eslint#1440]
## Issue Type
Bug

## Issue Description

[ESLint 8 is out now](https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0), and unfortunately `linter-eslint` does not support is as it uses the now-deprecated `CLIEngine` property. Migration docs can be found [here](https://eslint.org/docs/user-guide/migrating-to-7.0.0#the-cliengine-class-has-been-deprecated).

Logging this task to capture the work that will be needed to ensure ESLint 8 can be supported.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

**Comment by MRDGH2821** [comment]
Any update on this ?

**Comment by UziTech** [comment]
See https://github.com/AtomLinter/linter-eslint/pull/1442

**Comment by savetheclocktower** [comment]
The approach we seemed to land on in #1442 is the one I'd vote for: a new `linter-eslint-something` pakage hosted by the AtomLinter organization, where “something” perhaps indicates that this is only for ESLint v7 and greater. (Maybe `linter-eslint-modern` or something, except that's awful.) That way it can have its own distinct settings and doesn't have to preserve expected behavior that may only have been possible with the now-removed `CLIEngine` class.

Since the new package would spawn a worker process that needs to use the user's own version of Node, it would add a setting for `nodeBin` (and perhaps `eslintModulePath`) so that people could define those if `node` isn't in their path, or isn't the correct version. People who use NVM and need per-project versions of those settings could use [project-config](https://github.com/steelbrain/project-config/) or [atomic-managment](https://github.com/harmsk/atomic-management), or could define them via a `.linter-eslint` file.

Once that package exists, `linter-eslint` could be updated to notify the user whenever a project is using ESLint v8 or greater, and prompt them to install the new package if it's not already present. Since both `linter-eslint` and `linter-eslint-redux` (ugh, that's even worse) could both successfully lint using v7 — when `CLIEngine` was deprecated but not yet removed — `linter-eslint` would probably want to skip linting when it sees a v7 version of ESLint, **but only if** it knows that the other package is installed.

I'd be happy to help out with this if it would be welcomed; I've got a preliminary version of the find-the-user's-version-of-node code in a local package that's mainly just a port of @scagood's [proof-of-concept gist](https://gist.github.com/scagood/061ebc869de679abc1324ab184cdd4a0).

**Comment by UziTech** [comment]
@savetheclocktower I created [AtomLinter/linter-eslint-node](https://github.com/AtomLinter/linter-eslint-node) and invited you as a maintainer. If you want to create the initial version I can help you wherever you need.

**Comment by UziTech** [comment]
We just released [linter-eslint-node](https://atom.io/packages/linter-eslint-node) which should work with eslint v8. We created a new package for this because it required many breaking changes and we want people using linter-eslint successfully with older versions of eslint to be able to continue using it.
