### ISSUE TITLE
got eslint not found locally when using gulp-eslint

### ISSUE THREAD

**Issue by stevemao** [AtomLinter/linter-eslint#187]
would be great if it can search the deps tree.

**Comment by pitaj** [comment]
No, it would be great if it searched through the dependencies like a normal `require` would. Install `eslint` at the top level or use npm@3

**Comment by stevemao** [comment]
Yup, that's what I mean.

**Comment by pitaj** [comment]
`gulp-eslint` has `eslint` as a dependency, meaning that `eslint` is installed under the `node_modules` directory *inside* `gulp-eslint`. A normal `require` would not work for getting that `eslint`, as it only searches *upwards* through parent directories.

**Comment by stevemao** [comment]
true

**Comment by pitaj** [comment]
This would, therefore, be a completely exceptional change that would also be entirely unnecessary in the future (with npm@3 flattening dep structures)

**Comment by stevemao** [comment]
It would not be unnecessary coz the `eslint` lint might still be under `gulp-eslint` for some reason.
I think as long as this module checks one directory down it should be fine.

**Comment by pitaj** [comment]
This is a simple request with a simple solution on your side, and a very complicated solution on the maintainer's side.

**Comment by onlywei** [comment]
I have kind of a hacky solution on this issue here: https://github.com/AtomLinter/linter-eslint/pull/211

I realize that my solution is probably not ideal, but I also do not agree with @pitaj since build tools such as `gulp` are quite prevalent. Doing a local `npm install` of eslint just for one's text editor is just not acceptable in some teams. Saying that this is a "simple solution" on the user's side is not entirely accurate. Especially when you consider that:

* Not all teams all use the same text editor.
* Now you have to make sure the eslint versions between your `gulp-eslint` and your other eslint are in sync.

In my opinion a tool such as this one should actively try to support popular workflows, and do not try to mandate a specific setup to function. Sure, it's a somewhat complicated solution on the maintainer's side, but it's not THAT complicated, as demonstrated by my pull request.

**Comment by steelbrain** [comment]
Fixed by v5.0.0
