### ISSUE TITLE
Remove repeating "ESLint" in results area and allow visible double-clickable grippy for quick full collapse and expand

### ISSUE THREAD

**Issue by brettz9** [AtomLinter/linter-eslint#238]
And as an unimportant stylistic request, I would also suggest removing the repeating "ESLint" text in the error results area, unless you intend to allow multiple linting types together like "JSLint" as well. Otherwise, I think it is a little distracting (Maybe a small "ESLint" header could be at the top of the panel.

This request leads me into another related request to allow a panel heading which can not only be dragged, but also double-clicked to expand to its last-used height, or collapse fully except for a grippy.

**Comment by Arcanemagus** [comment]
You can disable showing this yourself by unchecking "Show Provider Name" in the `linter` package settings within Atom. As it seems like you noticed (or thought about?): This is _very_ useful when you have multiple `linter-*` providers that can all handle the same scope.

Your second point should be raised as a feature request over on the [`linter`](https://github.com/atom-community/linter) pacakge as `linter-eslint` has no UI of it's own.

I'm marking this issue as closed since none of it's parts are related to `linter-eslint`.
