### ISSUE TITLE
Upgraded to v3.2.0 and now `.eslintrc` is found but rules are ignored

### ISSUE THREAD

**Issue by danoc** [AtomLinter/linter-eslint#247]
Hello, myself and a coworker both noticed that upgrading to v3.2.0 has caused `linter-eslint` to ignore our `.eslintrc` file.

I stuck a `console.log` in the plugin source and noticed that it _was_ finding the path to our `.eslintrc` and `.eslintignore`, but it seems like the rules are not getting processed and only the default eslint rules are being applied. No errors or warnings are being thrown in the Atom console.

Any ideas what could cause this?

**Comment by SpainTrain** [comment]
My guess is the upgrade to eslint 1.x. In eslint 1.x rules are off by default (http://eslint.org/docs/user-guide/migrating-to-1.0.0.html)

**Comment by SpainTrain** [comment]
Can you run eslint via cli to see if you get the same behavior?

**Comment by danoc** [comment]
@SpainTrain – Where does the plugin find the bin for `eslint`? We're using a pre-1.0 version of `eslint` right now.

I'm trying to run it in the CLI but having unrelated issues. I'll report back if I get it to work.

**Comment by danoc** [comment]
This is the version that we use.
```
$ ./src/www/frontend/node_modules/.bin/eslint -v
v0.21.2
```
That executable works fine and follows my `.eslintrc` rules when I run through the CLI.

I don't have a global `eslint` though.
```
$ eslint
bash: eslint: command not found
```

**Comment by MikeDimmick** [comment]
I'm having the same problem - we're still using eslint 0.22.1 for this project and after upgrading to linter-eslint 3.2.1 it's complaining about a huge number of issues, which running eslint at the command line does not produce. Just as one example, our standard practice is to use single quotes, it's now complaining that every single string must use double quotes. This makes it completely unusable.

I'm running Atom 1.1.0 on Windows 7 64-bit. My setup is: 
* eslint 0.22.1 installed through npm in node_modules/.bin/eslint under the project root (where .eslintrc lives)
* atom installed to my %LocalAppData% folder C:\Users\*username*\AppData\Local\atom\app-1.1.0

I have tried installing eslint 0.22.1 globally, which placed it in C:\Program Files\nodejs. We use nvm-windows to manage the Node.js version: I'm currently using Node.js version 0.12.7. The problem still occurs when I select the 'Use Global Eslint' option, specifying either C:\Program Files\nodejs or C:\Users\*username*\AppData\Roaming\nvm\v0.12.7 as the Global Node Path.

I'd love to help debug it, but when I navigate to eslint.coffee in the debug tools, I just get a blank source window, making it impossible to debug.

**Comment by iam4x** [comment]
If you are using an old ESLint version, please use an older version of the plugin we dropped support.

`$ apm install linter-eslint@3.1.x`

**Comment by MikeDimmick** [comment]
I've just tried updating to eslint 1.7.3. It won't actually run on my project at the moment, because there's an incompatibility in our .eslintrc. linter-eslint is now producing the same error as running it from the command line, so it is loading the expected eslint - it's just using the wrong config.

The problematic commit is c5671ff, 'Lint javascript inside HTML file'. Reading the documentation for `CLIEngine.executeOnText`, it appears that it will only find an `.eslintrc` in the current working directory, unless we specify the path in the options.

Looking at the pull request https://github.com/AtomLinter/linter-eslint/pull/197, the author stated that plugins weren't supported - but the previous line of code loads any configured plugins, and I can confirm that our plugins were previously being loaded. We use the jasmine, require, requirejs and our own custom plugin. I don't immediately see why linter-eslint shouldn't load the html plugin in the same fashion and call `linter.verify` as before. However, I'm not using eslint on any source files with embedded JavaScript - this project is a pretty large Single Page Application using durandal.

As for dropped support - you said you dropped support for 0.20 and lower. I'm using 0.22 and @danoc is using 0.21, so we should still be supported.

**Comment by iam4x** [comment]
Sorry I meant to drop support < 1.0, we won't add back the code the load the plugins programatically.

You really should use an older version of the package.

**Comment by callmewhy** [comment]
> ESLint -v
v1.8.0

> Linter ESLint
v4.0.0

same problem...`.eslintrc` is found but rules are ignored
