### ISSUE TITLE
Please do not run custom linter if there is no custom config file for it.

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-eslint#25]
If there is no .jscsrc file, there is no need to run jscs linter and If there is no .jshint file, there is no need to run jshint linter etc

**Comment by matmuchrapna** [comment]
What do you think about setting this option to true, by default? or even get rid off it?

I found that everybody have it's own eslint configs, that's why it is unexpected behaviour to run atom-eslint with one predefined config for all plugin consumers. What do you think about it? (I can make pr for this)
