### ISSUE TITLE
Iinter-eslint ignores single files specified in .eslintignore

### ISSUE THREAD

**Issue by goffreder** [AtomLinter/linter-eslint#293]
It seems like linter-eslint is still ignoring single files specified in the .eslintignore file.

I have a .eslintignore with just the `webpack.config.js`specified but if I go to the file it still says I have a few errors in it. I also tried with another file that's nested inside my application and is parsed by webpack but it's linting it too. This doesn't happen if I lint the files from the CLI.

If I add `**/*.js` instead it's correctly ignored from the linting process.

**Comment by steelbrain** [comment]
Are you sure you are on the latest version of `linter-eslint`, also what's the output of the cli eslint?

**Comment by goffreder** [comment]
linter-eslint@5.2.0, I checked for updates but seems to be the latest version.

As for the CLI output (eslint@1.9.0):

    0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override
    ✖ 1 problem (0 errors, 1 warning)

**Comment by steelbrain** [comment]
That is weird, because I tested the feature myself and found it to be working. I'll test further soon

**Comment by goffreder** [comment]
Thank you. FYI, I've just updated to Atom 1.2.1, still not working. If you need more info, feel free to ask.

**Comment by steelbrain** [comment]
Yep, I can repro, let me try it with different eslint versions and find out why it worked back then

**Comment by steelbrain** [comment]
So I found out the problem, if there's a `.eslintignore` present the first time you lint, `eslint` only honors it then in the upcoming lint calls. It's an eslint agressive caching issue. The only "workaround" I can think of is by disabling/enabling the package or restarting atom every time you add or remove your `.eslintrc`.

We could fix this by poking into the internals of `eslint` and clearing it's cache after each lint call.

**Comment by shaungrady** [comment]
I'm having the same issue, though it applies to all my rules
```
app/assets/javascripts/application.js
app/assets/javascripts/vendor/*.js
spec/javascripts/
```
None of them seem to be applied until I prefix them with `**/` like @goffreder noted above

**Comment by steelbrain** [comment]
@shaungrady I don't think it's a bug for you, your `.eslintignore` **might** work for you in CLI because you pass it a relative path and a relative path is like `app/assets/a.js` but we in the package specify a full path like `/home/steel/app/assets/a.js`, which is the recommended way from the README. I had a look at the README section about `.eslintignore` yesterday and it showed that we need to use `**/*.js` or something to ignore all files.

  I am personally gonna prefer to support the format recommended by the documentation, but if you feel like I've missed something and relative paths should be used, breaking compatibility with the documented ones, please do let me know :)

**Comment by IanVS** [comment]
@steelbrain, I'm curious about this [comment](https://github.com/AtomLinter/linter-eslint/issues/293#issuecomment-157454294).  ESLint does not cache by default, and I can't see where you are telling it to cache.  Can you explain how you are using ESLint with caching?  I ask because I am also having other problems apparently related to linter-eslint and caching.

**Comment by steelbrain** [comment]
@IanVS Here's something from my experience, if you have a `.eslintignore` file and lint a file, then you remove that `.eslintignore` and retry to lint, it will throw an `ENOENT` error, meaning it is caching the existance of the file

**Comment by IanVS** [comment]
Hmm, that sounds like a bug in ESLint, then.  I'm guessing it's trying to check for the file to see if it's changed.  I'll take a quick look.

**Comment by IanVS** [comment]
I cannot reproduce.  I created an `.eslintignore` and added a filename (we'll call it `foo.js`).  When I linted `foo.js` with `eslint foo.js`, I get the expected warning that the file was ignored because of the `.eslintignore`.  Then I deleted the `.eslintignore` and linted `foo.js` again, and it returned with no errors.

I also tried running with `--cache`, then deleting `.eslintignore` and rerunning with `--cache`, and still experienced no errors.

Maybe you can give a reproducible test case?

**Comment by shaungrady** [comment]
@steelbrain Sorry, which README were you looking at? The [ESLint docs](http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories) about `.eslintignore` use relative paths, so does the [ESLint git repo](https://github.com/eslint/eslint/blob/master/.eslintignore). Requiring a full path makes it pretty useless when using `.gitignore` in a shared project repo. Am I misunderstanding?

**Comment by steelbrain** [comment]
@shaungrady http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories

**Comment by shaungrady** [comment]
Yeah, that's the one I linked to. I don't see anything about not using relative paths. :expressionless:

**Comment by steelbrain** [comment]
@shaungrady Oops, I misunderstood. Here's my :+1: on passing relative path to `eslint`.

**Comment by IanVS** [comment]
Yes, ESLint requires relative paths in the .eslintignore, if I recall correctly.

**Comment by steelbrain** [comment]
@IanVS I am busy with the base linter UI improvements and I'm gonna be busy with that for a day or two, mind taking this?

You should've recieved a few emails from GitHub

**Comment by IanVS** [comment]
Got them, thanks. 

I can try taking a look into this, but I'm also fairly busy adding automatic config generation for ESLint 2.0.
