### ISSUE TITLE
Using pwd in linter settings

### ISSUE THREAD

**Issue by kand** [AtomLinter/linter-eslint#337]
I have an ```.eslintrc``` file nested within a project directory to keep things tidy. However, I'm unsure how to specify where this file is in the settings for this plugin.

If I use a relative path in either ```ESLint Rules Dir``` or ```.eslintrc Path```, it ends up appending that path to the directory of the current file I'm trying to lint.

Is there a way to specify the current project directory so that I can use a nested ```.eslintrc```?

**Comment by IanVS** [comment]
You shouldn't need to specify the location, it will be detected automatically when you are linting files in that directory.  The only time you need to specify a path to your config is if you want to use a config which normally wouldn't be picked up by ESLint's [configuration cascade hierarchy](http://eslint.org/docs/user-guide/configuring.html#configuration-cascading-and-hierarchy).

**Comment by kand** [comment]
I'm still working on the best configuration, but we're using Docker and it makes it, arguably, easier to understand the project if I can keep the configs out of the project root and in a specific directory.

So in this case, the configuration cascade hierarchy won't work for me and I need to be able to configure in settings something like a relative path from the root of the project.

**Comment by IanVS** [comment]
Whether you're using Docker or not, I find it difficult to believe that it makes a lot of sense to break and then try to hack around the normal configuration cascade flow.  Could you perhaps achieve the same kind of separation of config by having config files in a parent directory?  

The problem is, linter-eslint has no real concept of a "project root", so I'm having a hard time imagining how this request could be implemented.

**Comment by kand** [comment]
I've opted to provide directions on having an ```.eslintrc``` at the root that extends the nested ```.eslintrc``` if devs want to have real time linting in their ide.

**Comment by IanVS** [comment]
:+1: Sounds like a good plan.
