### ISSUE TITLE
Use of `babel-eslint`

### ISSUE THREAD

**Issue by iam4x** [AtomLinter/linter-eslint#35]
I want to switch to eslint, since JSXHint is discontinued. But I wanted use `babel-eslint` plugin (https://github.com/babel/babel-eslint) for that I had to add it on `package.json`.

`linter-eslint` isn't looking for `eslint` system wide command, it should for using plugins.

So my question is, do we try to implement system wide `eslint` by default? Add `babel-eslint` in the package for people like me?

**Comment by pesho** [comment]
+1, especially now that [babel-eslint](https://github.com/babel/babel-eslint) has been "officially endorsed" by ESLint's author ([link](https://github.com/eslint/eslint/issues/1657#issuecomment-77500655)).

It would be great if `linter-eslint` either allowed us to set the path to a custom `eslint`/`babel-eslint` executable, or even better, already included `babel-eslint`.

**Comment by jfaissolle** [comment]
@pesho, I think the second solution would be easier to implement. But for now, you can use an eslint version local to your project. Personally, I tend to have it this way.

**Comment by ColCh** [comment]
First solution brings some flexibility ...

**Comment by kyriacos** [comment]
:+1: for either solution. I added the React plugin and i have a bunch of errors showing up in Atom :)

**Comment by tcoopman** [comment]
I believe it would be nice if linter-eslint would use eslint and babel-eslint first from node_modules, then global installed and only as a last resort use the coupled eslint version.

**Comment by AsaAyers** [comment]
@tcoopman linter-eslint does use the version of `eslint` it finds out of node_modules https://github.com/AtomLinter/linter-eslint/pull/32

**Comment by tcoopman** [comment]
Oh. I assumed this wasn't the case because it's not the case for babel-eslint. My bad!

Any reason why this doesn't work for babel-eslint then?

**Comment by AsaAyers** [comment]
I had never heard of `babel-eslint` at the time I made the PR. Maybe if you can get that going you can open a PR to add it.

**Comment by tcoopman** [comment]
Well, it would be nice for all plugins. For the plugin, it's coffee script (what I don't know) so I don't think I'll have time for a plugin soon.

**Comment by kyriacos** [comment]
Maybe #45 is all we need for the plugins at least that is. Not sure about babel-eslint.

**Comment by AsaAyers** [comment]
I don't make PRs for things I don't use. I suspect that's the same for whoever maintains linter-eslint. If you want babel-eslint I recommend digging into the code and adding it yourself.

If you don't know CoffeeScript take the hour or so it takes to read http://coffeescript.org/ top to bottom and you're ready, assuming you already know Javascript. I don't know why anyone would use ESLint and not know Javascript.

**Comment by jfaissolle** [comment]
As I stated above, you can use `babel-eslint` if you install it AND `eslint` locally. I think it is the best way to go for now because `eslint`, `babel` and `babel-eslint` are moving really fast. Putting them in you project allows you to follow as you like.

**Comment by yamalight** [comment]
Can we have a fallback to globally installed babel-eslint? Installing eslint and babel-eslint in each and every project you're working on is a bit of pain.

**Comment by fibric** [comment]
For me it does not work. `eslint` complains always about `undefined is not a function` on every js file and always on line 1..
![image](https://cloud.githubusercontent.com/assets/623932/6941929/0f01e940-d884-11e4-8c2f-1b4b77e77693.png)

In my local project I have installed `eslint` and `babel-eslint`
![image](https://cloud.githubusercontent.com/assets/623932/6942149/df349f58-d885-11e4-9c75-4b4b4b94bc3b.png)

In Atom developer tools I see only a message about `activate eslint`. So no errors, even not about `undefined is not a function`.
![image](https://cloud.githubusercontent.com/assets/623932/6942102/80cf8ff4-d885-11e4-838e-6769db7ea2b6.png)

All I need todo to enable this behavior is to create an `.eslintrc` file.
```json
{
  "env": {
    "node": true,
    "browser": true
  },
  "parser": "babel-eslint",
  "rules": {
    "space-after-keywords": "always",
    "quotes": "single"
  }
}
```

I've also tried to install `eslint` and `babel-eslint` globally but it doesn't have a possitive effect.
```
npm ls -g --depth 0
C:\Users\denny.trebbin\AppData\Roaming\npm
├── amok@0.10.1
├── babel@4.7.16
├── babel-eslint@2.0.2
├── bower@1.3.12
├── coffee-script@1.9.1
├── eslint@0.18.0
├── esprima-fb@13001.1001.0-dev-harmony-fb
├── generate-schema@2.1.1
├── gulp@3.8.11
├── jscs@1.11.3
├── npm@2.7.0
├── slush@1.1.1
└── yo@1.4.6
```
This issue is valid for my Windows7 company machine and my Mac Pro at home.

When I delete the `.eslintrc` file then no eslint errors are shown and of cause no linting at all.

Here are my Atom packages
```
C:\Users\denny.trebbin\.atom\packages (31)
├── atom-beautify@0.23.1
├── atom-color-highlight@3.0.8
├── atom-ctags@2.6.1
├── atom-ternjs@0.5.8
├── auto-indent@0.1.0
├── autocomplete-bibtex@0.5.6
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.7.1
├── duotone-dark-syntax@0.1.0
├── duotone-light-syntax@0.1.0
├── editorconfig@0.3.3
├── git-tab-status@1.6.0
├── highlight-column@0.4.0
├── highlight-line@0.10.1
├── highlight-selected@0.9.1
├── isotope-ui@2.0.0
├── linter@0.12.0
├── linter-coffeelint@0.2.0
├── linter-csslint@0.0.11
├── linter-eslint@0.5.0
├── newton-dark-syntax@1.1.1
├── newton-dark-ui@1.0.4
├── oceanic-next@0.1.1
├── preview-plus@1.1.19
├── project-manager@1.15.5
├── project-palette-finder@2.4.16
├── react@0.10.1
├── save-session
├── Stylus@0.6.2
└── text-manipulation@0.4.0
```

**Comment by AsaAyers** [comment]
> In my local project I have installed eslint and babel-eslint

Does this mean you ran `npm install eslint babel-eslint --save-dev` inside your project? And that `node_modules/eslint` and `node_modules/babel-eslint` exist?

**Comment by fibric** [comment]
Yes, as shown on 2nd screenshot.

**Comment by AsaAyers** [comment]
I wasn't sure because I can't see `node_modules`. What happens when you run eslint from the commandline?

**Comment by fibric** [comment]
content of projects `node_modules`
```
ls -Ahl node_modules\
total 46k
drwxr-xr-x    8 denny.tr Administ     4.0k Apr  1 15:03 .bin
drwxr-xr-x   14 denny.tr Administ     4.0k Apr  1 14:58 axios
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:51 babel-core
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:17 babel-eslint
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:51 babel-loader
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:58 css-loader
drwxr-xr-x    9 denny.tr Administ     4.0k Apr  1 15:03 eslint
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:04 eslint-loader
drwxr-xr-x    8 denny.tr Administ     4.0k Apr  1 15:26 eslint-plugin-react
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:59 file-loader
drwxr-xr-x   21 denny.tr Administ     4.0k Apr  1 14:57 flummox
drwxr-xr-x    8 denny.tr Administ     4.0k Apr  1 14:57 immutable
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:06 jasmine-core
drwxr-xr-x    1 denny.tr Administ        0 Apr  1 15:00 json-loader
drwxr-xr-x   16 denny.tr Administ     4.0k Apr  1 15:13 karma
drwxr-xr-x    6 denny.tr Administ        0 Apr  1 15:07 karma-chrome-launcher
drwxr-xr-x    5 denny.tr Administ        0 Apr  1 15:07 karma-firefox-launcher
drwxr-xr-x    1 denny.tr Administ        0 Apr  1 15:07 karma-ie-launcher
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:07 karma-jasmine
drwxr-xr-x    6 denny.tr Administ        0 Apr  1 15:07 karma-script-launcher
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:07 karma-webpack
drwxr-xr-x    1 denny.tr Administ        0 Apr  1 14:59 raw-loader
drwxr-xr-x    9 denny.tr Administ     4.0k Apr  1 14:56 react
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 15:04 react-hot-loader
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:56 react-router
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:59 style-loader
drwxr-xr-x    1 denny.tr Administ     4.0k Apr  1 14:59 url-loader
drwxr-xr-x   14 denny.tr Administ     4.0k Apr  1 15:00 webpack
drwxr-xr-x   10 denny.tr Administ     4.0k Apr  1 15:00 webpack-dev-server
```

local eslint
```
node_modules\.bin\eslint -v
v0.18.0
```

global eslint
```
eslint -v
v0.18.0
```

**Comment by AsaAyers** [comment]
does `node_modules\.bin\eslint` complain always about `undefined is not a function` on every js file? This will help determine if this is a bug with `linter-eslint` vs `eslint` or `babel-eslint`.

**Comment by fibric** [comment]
Running from console it doesn't complain about anything.
![image](https://cloud.githubusercontent.com/assets/623932/6943414/2f4061f0-d88e-11e4-8658-077de3e1fbf5.png)

Oh well maybe its about io.js
Locally I run io.js 1.6.2
But Atom on Windows still does run on old node.js 

```
apm -v
apm  0.149.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 1.9.4.msysgit.0
visual studio 2013
```

**Comment by fibric** [comment]
Here is the output with `Lint Debug` enabled.
Firstly I've opened `package.json` file to check if `linter-jsonlinter` works (implicitly assuming that the Linter API works just fine).
Then I've opened the `webpack.config.js` file. Note: I have installed no other js linter except `linter-eslint`.
![image](https://cloud.githubusercontent.com/assets/623932/6944799/fd546030-d895-11e4-9785-a01e140e4b6c.png)

The debug info says nothing to me. Maybe only something about `rulesDir`. The `rulesDir` variable is empty. I assume this causes `linter-eslint` to check for a project based `.eslinterc` file instead of a global one.

**Comment by fibric** [comment]
Here on my Mac I could reproduce the situation.
![image](https://cloud.githubusercontent.com/assets/623932/6947666/1751f502-d8a9-11e4-80bb-21c66fce78d0.png)

But I found when I rename or delete my `.eslintrc` file in project root then eslint works just fine, except it does not know about my rules. doublequote, really? ;-)
![image](https://cloud.githubusercontent.com/assets/623932/6947808/00764094-d8aa-11e4-9ea4-28e05f6f5da0.png)

**Comment by jfaissolle** [comment]
@fibric you did `npm ls -g`. This lists global packages. As stated previously by @AsaAyers and me, the linter-eslint plugin does not work with globally installed packages. You have to install eslint and babel-eslint locally in your project.

**Comment by ColCh** [comment]
I've installed **babel-eslint** as *local* dependency (`npm i babel-eslint`) for *linter-eslint* *apm* package. So, it works now :+1: 

But I'm not sure this is permanent... Will *node_modules* be rewritten after *linter-eslint* update?

*node_modules* path for *linter-eslint*:
```sh
/home/colch/.atom/packages/linter-eslint/node_modules
```
`npm ls --depth=0` for this directory
```sh
➜  node_modules  npm ls --depth=0 
linter-eslint@0.5.1 /home/colch/.atom/packages/linter-eslint
├── babel-eslint@2.0.2 extraneous
├── eslint@0.18.0
└── resolve@1.1.6
```

**Comment by jfaissolle** [comment]
@ColCh, when speaking about "local dependency", I was referring to your project, meaning the project you want to lint. Sure, it would also work like you did but I find it more reproducible and maintainable to add all dependencies (eslint, babel-eslint) in each project.

**Comment by iam4x** [comment]
We should add on `README.md` a note about using plugins and local eslint,

* `$ npm i --save-dev eslint babel-eslint`

voilà

**Comment by jfaissolle** [comment]
@iam4x agreed !

**Comment by Globegitter** [comment]
@jfaissolle is there any way for the plugin to also get the global installs of `eslint` and `babel-eslint`? In most of my projects I am using other plugins such as https://www.npmjs.com/package/mocha-eslint or https://www.npmjs.com/package/sails-hook-eslint which already install eslint. Also my node_modules folders on my disk are already large enough so would be great to have the option to keep that to a minimum.

**Comment by AsaAyers** [comment]
No, there isn't a way to get the global installs. Atom runs it's own copy of node (io.js?) and so its "global install" is not in the same place as `npm install -g ...`. Depending on how you installed node it might be in different places, so we aren't going to bypass the built in resolution system trying to go find it. We're able to find locally installed packages by running Node's resolution algorithm starting at the folder you're linting.

Your `package.json` *should* contain everything needed to work on your project. I'm telling you from experience, it's a major pain to join pain to try to contribute to a project where the original developer didn't bother to include every dependency just because he decided to use global installs for his projects.

**Comment by ColCh** [comment]
@AsaAyers see my previous message for "global" installation. You can "hacky" install *babel-eslint* as extraneous package. However, I don't recommend doing that :smile: 

BTW did you have CSSLinter inside of _package.json_? And _grunt-cli_, _mocha_, other launchable utils?

**Comment by tcoopman** [comment]
I've just updated to atom 0.190 and have this issue with linter-eslint 0.5.2

I have babel-eslint and eslint installed locally but it doesn't work.
"hacky" installing babel-eslint in the linter-eslint apm directory fixes this.

**Comment by ColCh** [comment]
So..., maybe add new package **linter-babel-eslint**? jk

**Comment by AsaAyers** [comment]
> BTW did you have other linters (for ex. CSSLinter) inside of package.json devDependencies section? And grunt-cli, mocha, other launchable utils? Hm... may be this is right way to handle tool mess...

`grunt-cli` is just the command, which loads `grunt` which you install locally. I don't use a CSS Linter (as I rarely write CSS), but I maintain CoffeeLint which uses a similar same strategy. You globally install the CLI, but any time it finds a local instance of CoffeeLint the CLI just dispatches out to your local install.

If I had my way I'd make `npm install -g` install the CLIs, but wouldn't allow anyone to `require()` anything global. All of the configuration for your project (which version of eslint you use is project configuration) belongs inside your project.

I think the right next step here is to add some debugging so that `linter-eslint` will report what it can or can't find locally.

**Comment by mikekidder** [comment]
Same issue as @tcoopman. I installed a local copy of eslint and babel-eslint in project. Getting the eslint error 'Undefined is not a function' error message on every file.

**Comment by IanVS** [comment]
@mikekidder, do you happen to be using the `key-spacing` rule with an `align` defined?

**Comment by IanVS** [comment]
@mikekidder if you're using 0.19.0, it could be because of: https://github.com/eslint/eslint/issues/2311

**Comment by mikekidder** [comment]
@IanVS thanks for info.  I was testing out [acdlite/flummox] (https://github.com/acdlite/flummox). 
As of this comment, Flummox is at **eslint@0.18.0** and **babel-eslint@2.0.2**.

Updating to **babel-eslint@3.0.1** and reloading the Atom IDE resolved.

**Comment by csaintc** [comment]
+1

I run my code in a docker container, so the node_modules I use is compiled for a different file system. Having to use my node_modules for the eslint plugin breaks
