### ISSUE TITLE
Not scanning whole project, but only a current file

### ISSUE THREAD

**Issue by Kamilius** [AtomLinter/linter-eslint#362]
The thing is, that my linter-eslint only scanning my current file, but I can't seem to find a way to scan whole project. How this can be enabled or forced?

**Comment by steelbrain** [comment]
It's designed to lint only current file :wink: 
That project tab just **organizes** messages for you, if you say have 3 text editors open, only active's errors will be shown with `File` tab, and all the editor's errors will be shown with `Project` tab

**Comment by Kamilius** [comment]
@steelbrain ok, thanks for information

**Comment by idan** [comment]
@steelbrain out of curiosity — what's the reason for restricting eslint from doing it all? Speed?

Asking because I could see utility in an additional lint command like 'lint everything" which costs more time but fills up the project view with all my lint errors

**Comment by steelbrain** [comment]
@idan There are several reasons that add up, some of them are

 - It's performance intensive
 - It's redundant, because sometimes you only want to edit one file quickly in a project and don't care about the rest
 - It's disturbing, imagine if you had lint errors from all the dist files in the project, that would make the project tab very useless

Point 3 can be worked around by creating a `.eslintignore` file, but not everybody would want to create that, people would just expect it to lint the current file (and that too, only when an `.eslintrc` is found). Another thing that I can think of is that we will have to lint the entire project first, then watch files for changes and refresh messages for that file, if we create this functionality here then we would be doing a lot of redundant job.

If we really want to add this functionality, I would rather have it in the helper module so all the linters depending on it can make use of it and this feature is available to a broader audience.

**Comment by idan** [comment]
@steelbrain I'm talking about a one-off command that gets run, not something that happens automatically. If you use it and don't have a `.eslintignore`, you'll have a bad time.

My current workaround is switching to a terminal and running eslint from there to make sure that I don't have any stray lint warnings in files I don't have open, and then return to atom and open each file.

When you say "helper module" you mean the main atom-linter vs `linter-eslint`?

**Comment by steelbrain** [comment]
When I say `helper module`, I mean the [`atom-linter`](https://github.com/atomlinter/atom-linter) npm module. One problem adding a command that lints the entire directory introduces is that the base linter  will be confused, this linter currently registers itself as a file-scoped linter, which means that the messages it returns for each text editor will be isolated to that editor and that base linter will manage them by itself. It will show messages from all opened editors of a single linter in the project tab.

If we add messages from the whole project for a file-scoped linter, it will add duplicate of all those messages for each editor. One **workaround** I can think of is to register two providers in this linter, one can be used as file-scoped and the other used as project-scoped. This is now possible with the linter indie API. But even then, we will have a problem, to refresh the messages in those text editors, you will have to again execute that lint project command and another command to clear them all from view.

**Comment by idan** [comment]
Mkay, sounds like too much collateral damage for the utility gained. Thanks!

**Comment by SpainTrain** [comment]
@idan https://atom.io/packages/atom-terminal-panel may help streamline the workflow you described in the short term.

**Comment by idan** [comment]
@SpainTrain brilliant, thank you!
