### ISSUE TITLE
Allow custom .eslintrc entry to override local .eslintrc in the project

### ISSUE THREAD

**Issue by mppatterson** [AtomLinter/linter-eslint#398]
When entering an .eslintrc path, there should be an option to override the local .eslintrc (instead of only using the custom .eslintrc when the local .eslintrc does not exist).

**Comment by IanVS** [comment]
Can you explain what your use case for this would be?  It seems like it would be dangerous to edit a file using different linting rules from what is specified for the project.

**Comment by albertosantini** [comment]
I second @IanVS.

Any feedback or closing?

**Comment by mppatterson** [comment]
Agreed, thanks for the input.  I was having some local issues with my eslintrc file but it turned out to be conflicting npm packages, so this is no longer needed.

**Comment by jeacott1** [comment]
this actually would be very handy for the case where you want to enforce for example 
"linebreak-style": ["error",  "unix" ], but have developers using both windows and linux environments for dev. the ability to be able to locally override features in a project would be extremely handy.

**Comment by IanVS** [comment]
We already have settings for `Disable specific rules from fixes` and `Silence specific rules while typing`.  Are those enough for your use case?

I'm not sure I understand why you would want to have a linting rule but then allow people to break it.  Maybe you can explain a little more?

**Comment by jeacott1** [comment]
because git converts lf to crlf and back again for windows users, so having your local ide read your .eslintrc file and smear the entire codebase in red is really annoying. having to comment out the linebreak-style and remember undo the change or not commit but still revert everytime a branch switch is required is also really annoying.

**Comment by IanVS** [comment]
I see.  So it's not enough to silence those rules while typing, you want to silence them after saves as well.  I could see possibly adding a `Silence specific rules` option, rather than a custom eslint config file.  Would that meet your needs?

**Comment by jeacott1** [comment]
maybe - its only that particular rule I want to suppress right now, but the ability to have environment variable overrides for example would be nice.  something like:
env var:  eslint.rules.linebreak-style= '["error", "unix" ]' for example.

**Comment by IanVS** [comment]
I believe you could do something like you want if you use the javascript version of an eslint config file (`.eslintrc.js`).  Then within that file, you could check for an environment variable and export a config based on that setting.  Because really what you're talking about is more than just changing the config within the atom editor, you want to change the config for windows users when they are running ESLint on the CLI as well, I assume.

**Comment by jeacott1** [comment]
sure - I'm not using atom btw, but js config might be an option. unfortunately I dont control the project so wouldn't be an easy fix.

**Comment by Arcanemagus** [comment]
@jeacott1 The proper way to fix your example is to create a `.gitattributes` file telling git to check out the files with the correct line ending, regardless of the platform it is checking them out on. You can see an example of that in this project itself [here](https://github.com/AtomLinter/linter-eslint/blob/v8.2.1/.gitattributes#L2) 😉.
