### ISSUE TITLE
Linter not working correctly when I install atom-beutify

### ISSUE THREAD

**Issue by Horray** [AtomLinter/linter-eslint#399]
I installed [atom][1], and I'm trying to add a eslinter. I added [linter][2] and [linter-eslint][3]. It worked fine until I added the [atom-beautify][4] package.

The linters does their jobs, but when I 'beautify' the JavaScript code, most errors in the code panel don't show, but they do show at the bottom. Here's what I mean:

**Before beautify the code:**

[![enter image description here][5]][5]

[![enter image description here][6]][6]

**After Beautify the code:**<br>
[![enter image description here][7]][7]<br>
[![enter image description here][8]][8]

How can I get the errors to show even after I beautify the code?

Here's a list of all Community Packages:

- atom-beautify
- linter
- linter-eslint

  [1]: https://atom.io/
  [2]: https://atom.io/packages/linter
  [3]: https://atom.io/packages/linter-eslint
  [4]: https://atom.io/packages/atom-beautify
  [5]: http://i.stack.imgur.com/hdDNO.png
  [6]: http://i.stack.imgur.com/RJwSA.png
  [7]: http://i.stack.imgur.com/tV60F.png
  [8]: http://i.stack.imgur.com/5DaRm.png

**Comment by Arcanemagus** [comment]
I imagine what is going on here is atom-beautify is modifying the code in question, which means the markers placed on that code are no longer valid so they are removed. Since a lint hasn't been triggered yet the messages still show in the bottom panel.

This isn't really anything that can be fixed here, you can workaround this by triggering another lint either by typing some more code, or saving the file (depending on your settings). Or by running `Linter: Lint` from the command palette.

Let us know if that is what is going on here or if there is something more subtle at play.

**Comment by Arcanemagus** [comment]
Closing in favor of https://github.com/atom-community/linter/issues/1042.
