### ISSUE TITLE
Does not work with eslint plugin processors

### ISSUE THREAD

**Issue by TGOlson** [AtomLinter/linter-eslint#52]
Hello, I am currently writing an `eslint` plugin that makes use of the new [processors](http://eslint.org/docs/developer-guide/working-with-plugins) option. However, `linter-eslint` doesn't seem to recognize or run the processors.

For example, my root plugin file looks something like this:

```js
module.exports = {
  rules: {
    'my-rule': require('path/to/rule')
  },
  rulesConfig: {
    'my-rule': 2
  },
  processors: {
    '.sjs': require('path/to/processor')
  }
};
```

When I run `eslint` from the command line against a `.sjs` file everything works as expected, and my processor is invoked. However, when I open up Atom, the eslint linter does not run my processor.

Any ideas? Is this a bug or a feature that was omitted? It would be really great to be able to use the processor feature from within a live linter environment.

Edit: looks like the processor feature for plugins was introduced in version [0.16.0](https://github.com/eslint/eslint/blob/master/CHANGELOG.md), less than a month ago. I have the latest `eslint` in my local node modules, and it seems `linter-eslint` knows to use that version, but still the feature is not compatible.

**Comment by jfaissolle** [comment]
Can you try to install eslint, your processor and plugin in the project to be linted ? This should work. linter-eslint does not use globally installed packages. Only local ones.

**Comment by TGOlson** [comment]
Ya, everything is installed locally - it works when I run eslint from the command line (that is, eslint passes my processor the file, etc.). 

After some digging, it seems that the core problem is that the eslint api does not run the processors - only the cli engine does that. I opened a similar issue over at the eslint repo (you can see it [here](https://github.com/eslint/eslint/issues/2231), but they seem unwilling to change it.

One possible work around is to call the CLIEngine instead of `eslint.verify` from the linter. I'm not sure if this is preferable, but it is possible. I hacked around and got a proof of concept working by doing something like this:

```coffee
// Current version that uses the elint api
result = linter.verify @editor.getText(), config

// Possible new version that uses the CLIEngine
// Note: this might not be the exact process, I lost my hacked version of the linter
// But it is something like this
results = engine.executeOnFiles [@editor.getText()]
result = results[0].messages
```

**Comment by jfaissolle** [comment]
The only API of eslint that does execute processors is `executeOnFiles` but we cannot use it. 
In the linter subplugins (like linter-eslint), there is two ways of working in order to lint the file while it is being edited by the user:
- lint the temporary file generated by the linter plugin. This was the original way of linting of the linter-eslint plugin. It used to call the eslint command line directly.
- lint the buffer content. This is how linter-eslint currently works.

The eslint API `executeOnFiles` function works exactly like the command line. The problem is that if we pass it the temporary file generated by the mother linter plugin in /tmp, the configuration is not computed correctly. It does not take into account the full .eslint file hierarchy for example. If we operate on the real file path, the configuration is correct but there is no mean to lint in real time (while the user is typing). The linting can only be done on file save.

Note that the other API method, `executeOnText` does not take into accout the config hierarchy and does not execute processors so we cannot use it.

The problem of not processing the .eslintrc file hierarchy is that the behavior is different from the command line execution. The transition to the current `linter.verify` way was done for #9 . The eslint team was kind enough to provide some helpers in CLIEngine to get the config object (`getConfigForFile`) and excluded files (`isPathIgnored`). But it was not easy to obtain.

Ideally, it would be great if we could have a function in the API like `executeOnTextWithConfig(text, config)` or `executeOnTextWithConfigFromPath(text, path)` but it would be hard to obtain. I think the easiest way now would be to reimplement the processor execution part of eslint.

I do not know if my answer was clear.

**Comment by miljan-aleksic** [comment]
I also have a processor and I see the limitation of the API but is not clear to me if there is any solution or workaround I missed.

**Comment by iam4x** [comment]
@miljan-aleksic Is this still happening with newer versions of the package? If yes could you set me an reproduction case?

**Comment by miljan-aleksic** [comment]
@iam4x, with new versions is recognising custom plugins (at least not more notices about missing plugins) but is still not processing them. The plugin I'm testing is the eslint-plugin-html and a simple file with a script tag inside where the wrapped JS is totally ignored. Should I open a new ticket about this?

**Comment by iam4x** [comment]
@miljan-aleksic I'm going to fully rewrite `linter-eslint` to use the CLI, we will stop to have theses issues. This is happening tomorrow :+1:

**Comment by miljan-aleksic** [comment]
wow! count on me for testing!

**Comment by TGOlson** [comment]
:+1:

**Comment by iam4x** [comment]
Version 2.0 has been released now using CLI, please open a new issue if something is wrong.
