### ISSUE TITLE
Allow disabling job complete popup box when running `fix-file` command

### ISSUE THREAD

**Issue by vjpr** [AtomLinter/linter-eslint#538]
https://github.com/AtomLinter/linter-eslint/blob/0203b38bd5c206b5b992c0e10028ccb1161928ee/lib/worker.js#L40

**Comment by IanVS** [comment]
Hi, can you explain why you think the status should be able to be disabled?  I think it provides valuable feedback whether all errors could be fixed or not (ESLint does not always fix everything).

**Comment by pvamshi** [comment]
Now we can do the same job by enabling "fix on save" . This option fixes silently. Explicitly calling "fix-file" should provide a status "success" or "failure" in my opinion.

**Comment by vjpr** [comment]
> can you explain why you think the status should be able to be disabled?

Its something I run very often, and I prefer not to have my code "fix on
save".

I treat it the same as a code formatter. I don't know of another editor/IDE
that shows a popup notification when it finishes code formatting/linting. I
think popups should not be too frequent, otherwise they are annoying. They
demand attention and obfuscate a part of the editor.

Something less intrusive. Maybe in the status bar perhaps to show it was
successful.

**Comment by pvamshi** [comment]
I think its personal choice. I agree it irritates sometimes to see the status when you already know its done with formatting. 
If everyone agrees, we can have a setting . May be silent mode and prevent showing the success messages .

 But personally I cant agree we should never show the success message. 
Sometimes there is nothing to fix or some error can not be fixed by "fix-file" command . In that case the error still stays, the user don't know if the task is run and it didn't get fixed or the task was not run at all .

**Comment by IanVS** [comment]
@pvamshi, @vjpr asked for an option, not that we disable the notification altogether.  

@Arcanemagus what do you think?  I'm not convinced that it warrants a setting, but don't feel strongly either way.

**Comment by Arcanemagus** [comment]
Hmmmm, the only problem I have with an option is that for most users it will just be useless clutter. Personally at least I'd say no, but I never use that functionality so I don't really have a basis for an opinion.

Since it seems neither of us really have a strong opinion either way on the matter I wouldn't be opposed to a PR implementing such a setting.

**Comment by IanVS** [comment]
This has been open for more than 8 months with no PRs submitted.  That indicates to me that it was not important enough for anyone to act on, so I'm going to close the issue to reduce noise in the open issues.
