### ISSUE TITLE
Add hotkey to auto-lint

### ISSUE THREAD

**Issue by chalda** [AtomLinter/linter-eslint#575]
Thanks for a great plugin! I love the auto lint feature that fixes everything that super-extra-sensitive lint config that my crazy coworkers have automagically. However there are some files that I dont want to fix (written by other devs) is it possible to put this feature on a hotkey so it auto-lints the file when i hit it instead of on save.

**Comment by Arcanemagus** [comment]
You can't selectively toggle it automatically, but if you enable/disable the auto-fix yourself, you can create a keybind of your own by editing your keymap file.

I'm not familiar with it myself, but I believe you would do something like this:

```cson
'atom-text-editor:not([mini])':
  'ctrl-alt-[': 'linter-eslint:fix-file'
```

Obviously replacing `ctrl-alt-[` with the combination of your choice.

I'm going to mark this as closed since there isn't anything more that can really be done as far as this package is concerned, but if you run into any issues getting that working please post back!

**Comment by chalda** [comment]
@Arcanemagus hey thanks for the tip! ive been doing this manually (which is kind of a pain in the ass) this would definitely help. this should work well enough thanks for the help!

**Comment by Arcanemagus** [comment]
If you wanted to get real adventurous you could write your own function in your init script that toggles the "Enable auto-fix" setting, and then bind a key to that as well.

**Comment by chalda** [comment]
Hahahaha didnt even see your comment but was actually doing just that :D

This might be valuable to someone else so may be worth writing in an FAQ somewhere if you have one:
This is my init script addition:
atom.commands.add 'atom-text-editor', 'custom:toggle-eslint-fixOnSave', ->
    fixOnSaveValue = atom.config.get('linter-eslint.fixOnSave')
    atom.config.set('linter-eslint.fixOnSave', !fixOnSaveValue)

'atom-text-editor:not([mini])':
    'cmd-alt-l': 'linter-eslint:fix-file'
    'cmd-alt-o': 'custom:toggle-eslint-fixOnSave'
