### ISSUE TITLE
Linting .vue files

### ISSUE THREAD

**Issue by sebastiandedeyne** [AtomLinter/linter-eslint#576]
The linter doesn't seem to recognise javascript in `.vue` files.

I played around a bit, and when I add `'text.html.vue'` to `this.scopes`, it seems to work. Not sure if this is the way to go though, is this something that should be resolved here (in that case I'll send a PR with my changes), or in the language repository?

I'm using the language-vue package: https://atom.io/packages/language-vue

**Comment by sebastiandedeyne** [comment]
Opened this issue a bit too soon, only did a search in this repo, not in the language's. If anyone else has similar issues: here's the solution:

https://github.com/hedefalk/atom-vue/issues/16#issuecomment-177169198

**Comment by Arcanemagus** [comment]
Glad you got it figured out :wink:.

**Comment by gluons** [comment]
> The solution is to enable "Linter HTML Files" in the settings of linter-eslint and install eslint-plugin-html.

Thank you. It work! :bowing_woman:

**Comment by mikestopcontinues** [comment]
Unfortunately, this solution doesn't work when using `eslint-plugin-vue` rather than `eslint-plugin-html`. I think this topic warrants reopening.

**Comment by Arcanemagus** [comment]
@mikestopcontinues The problem with activation of this provider has _nothing_ to do with your ESLint configuration, but with your Atom `language-*` packages. The above option simply adds `source.js.embedded.html` to the list of scopes. If you are using a different `language-*` package to provide Vue support in Atom from what the others have been using it's possible that the scope needs to be customized.

Place your cursor within an embedded JS section and run `Editor: Log Cursor Scopes` from the Command Palette in order to see what your setup is marking it as. When you have found the most specific `source` line, put that in the custom scopes setting.

**Comment by mikestopcontinues** [comment]
Ahh, thanks!

**Comment by mokkabonna** [comment]
Any chance to automatically add scope `text.html.vue` if eslint config contains `vue`? It is required to lint .vue files.

**Comment by Arcanemagus** [comment]
> Any chance to add scope text.html.vue by default?

Definitely not, at least until ESLint supports Vue by default which is highly unlikely to happen.

> And other scopes like source.js.jsx are already added.

`source.js.jsx` is in there because the language package that adds support for it overrides regular JavaScript and forces it to be "JSX", even though it isn't.

**Comment by mokkabonna** [comment]
And as an option? Like linting HTML files. That also adds a non-default scope and requires a custom plugin to work.

**Comment by Arcanemagus** [comment]
The [scopes setting](https://github.com/AtomLinter/linter-eslint/blob/7f791653480ce30c1ffe9ab99c6c84e34fe7e7fe/package.json#L78-L91) is already there for _any_ scope that denotes something ESLint can parse. The only reason `lintHtmlFiles` is there is because it existed before the `scopes` setting was implemented. In fact, it seems that was the _first_ option implemented (https://github.com/AtomLinter/linter-eslint/commit/886207a08444f8a439979b0f09f441af8abec149) 😆.

**Comment by mokkabonna** [comment]
OK, thanks for taking the time to respond anyway :)

**Comment by skylize** [comment]
Perhaps you should file an issue with [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue/issues) asking them to support Atom out of the box.

**Comment by Arcanemagus** [comment]
@skylize This isn't anything to do with `eslint-plugin-vue`, other than them existing so it is a question in the first place 😛.

**Comment by skylize** [comment]
Oh, I get it now, after re-reading the thread several times. Haha

I think it would nice to expose the scopes setting to 3rd party plugins, so for instance `eslint-plugin-vue` could inject vue files into the scope. But I guess that would mean attempting to run on _every_ file, in case there is an injected scope. Gross. ☹️

**Comment by anthonydito** [comment]
My issue was solved with instructions found at https://alligator.io/vuejs/vue-eslint-plugin/

**Comment by francoism90** [comment]
> > The solution is to enable "Linter HTML Files" in the settings of linter-eslint and install eslint-plugin-html.
> 
> Thank you. It work! bowing_woman

Reminder: It's not needed to add `"html"` to plugins.

**Comment by turigeza** [comment]
@anthonydito For this didn't work : ( Is it still working for you ?
