### ISSUE TITLE
Only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by kachkaev** [AtomLinter/linter-eslint#598]
Hey guys,

I'm facing a rather strange error here and the most confusing part is that it only shows up in Atom linter, but not when I run `eslint` from the command line.

I don't have any global npm packages at all, so I don't think there is a change that two different linters are being used. My project's `.eslintrc` just contains one `extends`, which leads to a custom npm module (`eslint-config-my-commons`). That module contains some shared rules just like the famous airbnb's eslint config except that it also has some meteor dependencies. The reason for doing so is because I want to manage multiple meteor apps and keep all linter rules in one place.

Calling `npm run lint-js` (given that `"lint-js": "eslint ."` in `package.json`) from a console adequately returns errors and warnings, which I do expect to see. However, when Atom tries to use the same local linter, it shows me this:

```
Error: Failed to load plugin meteor: only one instance of babel-polyfill is allowed Referenced from: /path/to/project/.eslintrc
Error: Failed to load plugin meteor: only one instance of babel-polyfill is allowed
Referenced from: /path/to/project/.eslintrc
    at Object.<anonymous> (/path/to/project/node_modules/babel-polyfill/lib/index.js:12:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/path/to/project/node_modules/eslint-plugin-meteor/dist/index.js:8:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```
The error shows up with every little move I make despite that command-line linter works perfectly.

Not sure if it helps, but here's my `node_modules/eslint-config-my-commons/index.js`:
```js
module.exports = {
  'parserOptions': {
    'ecmaVersion': 6,
    'sourceType': 'module',
  },
  'extends': [
    'airbnb',
    'plugin:meteor/recommended',
  ],
  'envs': {
    'meteor': true,
  },
  'plugins': [
    'import',
    'meteor',
  ],
  'rules': {},
  'settings': {
    'import/resolver': 'meteor',
  },
};
```
What could go wrong?

**Comment by Arcanemagus** [comment]
I have no idea what is going on here unfortunately... it sounds like `babel-polyfill` has some check that multiple versions aren't being loaded, since this package has nothing to do with that, and `eslint` is working for you from the CLI I can only assume that it has something to do with Atom... but we are running `eslint` in a worker thread that _should_ be isolated from Atom.

I'll try to get some time to debug this further later...

**Comment by andreasloskan** [comment]
+1

**Comment by IanVS** [comment]
`babel-polyfill` is globally imported by `eslint-plugin-meteor` [here](https://github.com/dferber90/eslint-plugin-meteor/blob/master/lib/index.js#L1), My guess is that one of the other plugins you are using also imports `babel-polyfill`.  You could try turning off your other plugins, verify the issue is solved, and then turn them back on one by one to isolate out which one it is.

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed since this has absolutely nothing to do with this package. If you are experiencing this try running through the troubleshooting outlined by @IanVS above.

**Comment by HectorRPL** [comment]
If you follow tutorial angular-meteor socially this lines works for me

`#meteor remove urigo:static-templates`
`#meteor add angular-templates`

Remember that the html imports must be

```
import './helloWorld.html';
...
templateUrl: `imports/ui/components/${name}/${name}.html`,
```

**Comment by srokatonie** [comment]
In my case (Angular Meteor) I use `urigo:static-templates` and therefore I had to replace 
`templateUrl` with `template` in component setup and it worked.
