### ISSUE TITLE
gui modifications persist after uninstalling

### ISSUE THREAD

**Issue by aryzing** [AtomLinter/linter-eslint#612]
After uninstalling linter-eslint, the gui modifications made by the package persist: 
* the margin where the colored circles go remains at the same width as when the package is installed
* the "File 0, Project, 0 :heavy_check_mark: No Issues" indicator in the footer status bar persists.

I would like to fix these issues, any recommendations?

**Comment by aryzing** [comment]
Had to also remove `linter` package for the gui changes to go away. I'm pretty sure I did not install that package, is it possible it was installed with `linter-eslint`?

**Comment by Arcanemagus** [comment]
`linter-eslint` will install that for you since otherwise the package does absolutely nothing since it is just a service provider and has no interface of its own. As you saw you need to uninstall `linter` as well to remove the UI.

(The Nuclide package suite can also use linter providers, so `linter` isn't forced _active_ if it was disabled, only installed.)
