### ISSUE TITLE
Error: Cannot find module 'eslint-config-rackt' 

### ISSUE THREAD

**Issue by futurefeeling** [AtomLinter/linter-eslint#626]
![image](https://cloud.githubusercontent.com/assets/9881593/16515943/84ac695a-3fa7-11e6-8f62-d92ffec3c41f.png)

**Comment by LumpyChen** [comment]
Same problem.

**Comment by IanVS** [comment]
Do you have `eslint-config-rackt` installed in your project?  What is the output of `npm ls eslint-config-rackt --depth=0`?

**Comment by LumpyChen** [comment]
Of course we set our package without an error.
When we run the command `npm run lint` which has been written in `package.json` as `eslint xxx`( It adopts `eslint.js` in project's `node_modules`),
it goes well, while things turn wrong as I use `linter eslint` in atom.
What I believe the problem is that `linter-eslint` always fails to access `eslint.js` in the project and then access the `eslint`in global.
This might be the reason why package 'eslint-config-xx' always fail to be found, even it has been set correctly in `.eslintrc`

**Comment by dgautsch** [comment]
Possible duplicate of #489

**Comment by futurefeeling** [comment]
`npm install -g eslint && eslint-config-reckt` solved.

thanks for all replies

**Comment by HiroAgustin** [comment]
@futurefeeling just in case some dumbass (like myself) is copy-pasting you answer, it should be `rackt` not `reckt`.

**Comment by Arcanemagus** [comment]
@HiroAgustin edited @futurefeeling's post to account for that, thanks for the note 😉.
