### ISSUE TITLE
Don't lint files in node_modules

### ISSUE THREAD

**Issue by piuccio** [AtomLinter/linter-eslint#645]
If you open a file in your `node_modules` folder, `linter-aslint` tries to lint it.

Note that according to [eslint doc](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories), quote:

> In addition to any patterns in a .eslintignore file, ESLint always ignores files in /node_modules/* and /bower_components/*.

**Comment by Arcanemagus** [comment]
We're specifying the filename to `eslint`, so I'm not sure why it would be running on those. If so that's likely a bug in `eslint` for ignoring that for `stdin` input.

However, is there a reason you don't have that folder ignored in your VCS? By default `linter` (which runs `linter-eslint` ignores all files ignored by your VCS.

**Comment by piuccio** [comment]
Well the problem is exactly that if I want to debug one of the node_modules used in my application and I open any file in that folder, it gets linted.

I guess linter-eslint shouldn't even invoke eslint if an open file is inside node_modules

**Comment by IanVS** [comment]
Can you share your `.eslintignore`?

**Comment by piuccio** [comment]
I don't have any

**Comment by IanVS** [comment]
Interesting.  What versions of ESLint and linter-eslint are you using?

**Comment by piuccio** [comment]
If you want to reproduce on the actual project I'm working on, these are the steps

* Clone https://github.com/guardian/comment-count-widget
* npm install
* Open the folder in Atom (comment-count-widget)
* Double click on src/index.js -> the file is error free
* From the file tree bar, double click on `node_modules/rollup/dist/rollup.js`
* Observe lint errors being reported

I'm expecting the file to be ignored even if I've opened it in the editor.

I'm not sure what version I'm using because I've already left the office, but I've updated all packages a week or so ago. I can check again tomorrow.

**Comment by IanVS** [comment]
I'm not able to reproduce the problem in following the steps you provided.

![image](https://cloud.githubusercontent.com/assets/4616705/17032858/618e3500-4f49-11e6-82ad-8bda5abc5b34.png)

I'm using atom 1.8, and linter-eslint 7.2.4.  

I'm not sure what would be causing the behavior you're seeing.  Have you tried quitting and restarting Atom lately?  (Unfortunately, I've seen that fix way too many oddball problems.)  The other thing you can check is whether you have a `.eslintignore` in a parent or ancestor directory (or your home dir).  There are ways to unignore `node_modules` in an `.eslintignore` file, which is why I'm suspicious you might have one somewhere.

**Comment by piuccio** [comment]
:astonished:  I'll try tomorrow morning, thanks. Why didn't I think of turning it off and on again? :tongue:

**Comment by piuccio** [comment]
Indeed restarting Atom fixed the problem 😑 

thanks
