### ISSUE TITLE
Bump eslint dependency to v3

### ISSUE THREAD

**Issue by mattcollier** [AtomLinter/linter-eslint#672]
esling v3.0.0 was released on July 1, 2016: https://github.com/eslint/eslint/releases

Maybe there's a reason why v2 is still being used?

I have manually updated the linter-eslint package.json, did npm install and so far I have not encountered any issues.

**Comment by Arcanemagus** [comment]
Atom's package installer `apm` currently only bundles Node.js v0.10.40, `eslint@3` requires Node.js v4 minimum to install. As such we can't update the _bundled_ version until Atom v1.10.0 lands on stable as otherwise this package couldn't be installed 😛.

If you install `eslint@3` locally in your project this package should work with it just fine as the only thing it is missing out on are some convenience functionality that makes no difference to the end user.

For more details check out https://github.com/AtomLinter/linter-eslint/pull/671 for the planned work on updating when Atom v1.10.0 lands on stable.

**Comment by kevinSuttle** [comment]
This probably explains why Atom isn't picking up errors, but the CLI is...

**Comment by IanVS** [comment]
@kevinSuttle that shouldn't be the case at all.  Can you open an issue with the details of the problem you're having, including where you have ESLint installed, what version is installed, and a reproducible set of steps?  Also, have you restarted Atom lately?

**Comment by kevinSuttle** [comment]
@IanVS Follow-up: https://github.com/eslint/eslint/issues/3782#issuecomment-242533649
