### ISSUE TITLE
Race condition between Fixer and placing lint markers

### ISSUE THREAD

**Issue by JonathanWolfe** [AtomLinter/linter-eslint#701]
[Extracting my comments from #700 into it's own issue]

Currently, there appears to be a race condition between the Fixer and the placement of lint markers which will cause an error just like in #700.  The linter will try to attach a marker to a segment of code, but the fixer has just emptied the editor window and is replacing it with the fixed code.

Longer code obviously encourages this to happen. I see it every twenty or so saves on files that are ~150-300 lines long.

**Comment by Arcanemagus** [comment]
This is actually a bug in Atom, for some reason when a file updates outside Atom it has a step in the undo history where the editor contents are entirely blank, and _then_ updated to the new contents.

Of course even if that bug wasn't there, this would still pose problems as Linter asks `linter-eslint` to run on the file when it saves, at the same time the "fix-on-save" command from this package is triggered. Since the lint results will be from the pre-fix state, there will still be conflicts.

The only way I know to prevent this issue is moving from a regular linter provider to utilizing the Linter Indie API, allowing us to provide different behavior for the on-save event, and the on-the-fly event.

**Comment by JonathanWolfe** [comment]
If "fix-on-save" is turned on, couldn't we just fire the fixer event on save and have it call the linter after it's done instead of firing both events?

**Comment by Arcanemagus** [comment]
Nope, `linter-eslint` and `linter` are _both_ observers of the `TextEditor::onDidSave()` event. When `linter-eslint`'s handler gets called, it calls out to `eslint` to fix the file. When `linter`'s handler gets called it triggers `linter-eslint`'s `lint()` function. Since both packages are independently observing that event, there is no way to have one wait on the other, since they have no idea what the other is doing.

If we re-write this package to use the Linter Indie API, we move to a different event flow, where we can do different things depending on if the triggering event was a save or modification. So for example we could do the same thing we do currently for modifications, but for a save event if the user has enabled "fix-on-save" we could run that first before returning any lint results.

**Comment by JonathanWolfe** [comment]
Damn, that's really inconvenient.

**Comment by Arcanemagus** [comment]
Figured out a simpler way of doing it, that fixes some problems seen with `lintOnFly` calls as well. It's up in #703 and _should_ handle this as well.

I'm assuming that the flow once that lands will be:

* File is saved, `fix-on-save` is triggered by `linter-eslint`, `lint` is triggered by `linter`
  * If the `lint` call returns first, it marks up the file, then Atom handles any changes in the marker positions introduced by the fix run for us. Everything is happy.
  * If the `fix-on-save` finishes first, now the `lint` call will see that the text has been changed and drop the results
* The `fix-on-save` run _should_ trigger a new `lint-on-fly` lint call, since it modifies the file. This call will run, and assuming more changes haven't been made to the file it will complete and the new marker positions (if any) will be sent to Linter

Once that lands and is released we'll see if it works as I'm thinking 😛.

**Comment by Arcanemagus** [comment]
v7.3.2 includes this fix, can you check if you still hit issues with fix-on-save enabled?

**Comment by JonathanWolfe** [comment]
Seems to be working after half a day of usage.

**Comment by Arcanemagus** [comment]
Awesome, marking this as closed then.
