### ISSUE TITLE
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.)

### ISSUE THREAD

**Issue by AddictArts** [AtomLinter/linter-eslint#732]
Lately updating aslant has been scary and failing to mark lines 
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.)
    at .atom/packages/linter-eslint/lib/main.js:227:21
    at Array.map (native)
    at .atom/packages/linter-eslint/lib/main.js:192:27

**Comment by AddictArts** [comment]
Updating the local eslint fixed the issue. I just guessed and that fixed it. It would be better if it somehow could gracefully encourage the right version of eslint.

**Comment by Arcanemagus** [comment]
That particular error was fixed in ESLint v3.5.0.

The message you saw is a generic message thrown whenever an invalid coordinate is given from ESLint, as that (should) indicate a problem in what ESLint is telling you, we aren't filtering it out. We also can't really make it tell you the "right version" as that is almost always the latest version, and we would have to start building up a database of known bugs in ESLint and when they were fixed.

**Comment by IanVS** [comment]
Thanks, but we unfortunately can't anticipate errors from eslint and print a nice message.  There have been a number of issues on this repo with that error and we have instructed each time to update to eslint 3.5.0 or above. Hopefully that will help people to find the solution.
