### ISSUE TITLE
Line separator support

### ISSUE THREAD

**Issue by chemitaxis** [AtomLinter/linter-eslint#746]
## Issue Type
Bug

![screen shot 2016-11-07 at 19 57 39](https://cloud.githubusercontent.com/assets/1420409/20071441/d5c9629c-a524-11e6-94fa-07f6190bd35b.png)

## Issue Description
I have cloned this project from [GitHub](https://github.com/sahat/hackathon-starter) (very famous project). Removed eslint configuration from package.json and config my .eslintrc like this:

```
{
  "extends": [
    "airbnb",
    "jquery",
  ],
  "env": {
        "browser": true,
        "node": true
    }
}
```

The erros is solved if a remove this line from my app.js ([this file](https://github.com/sahat/hackathon-starter/blob/master/app.js)).

```
console.log('%s App is running at http://localhost:%d in %s mode', chalk.green('✓'), app.get('port'), app.get('env')); 
```

## Bug Checklist
Done.

For some information, in VSCode the error is not throwing. 
Atom vesion: 1.11.2
eslint -v
v3.9.1

Thanks!!

**Comment by chemitaxis** [comment]
Ok, if I add this to the top of the file, the error is gone... but, why? Thanks.

`/* eslint no-console: "error" */`

**Comment by not-an-aardvark** [comment]
I was looking into it because I thought it might be another bug with ESLint's locations, but this appears to actually be a linter-eslint bug.

At the end of [line 226](https://github.com/sahat/hackathon-starter/blob/63af577fd85ade26b966f24c2aa8ad36e0a41343/app.js#L226) in app.js, there is a `\u2028` "line separator" character. This is equivalent to a linebreak in JS, but appearently Atom doesn't count it as a linebreak. After that line, all of ESLint's error locations take the \u2028 character into account, so atom-linter attempts to mark the wrong line for errors after that.

Simple repro case:

```js
/* eslint semi: error */

// There is a \u2028 character after this line.
 
foo
```

**Comment by Arcanemagus** [comment]
@not-an-aardvark That definitely sounds like an Atom bug, can you [file an issue](https://github.com/atom/atom/issues/new) over there about this?

We rely on Atom to know what it's doing as far as what lines are where 😛.

**Comment by not-an-aardvark** [comment]
I'm not sure this is actually a bug in atom itself; it has to support many languages, most of which probably don't consider `\u2028` and `\u2029` as linebreaks. If anything, this would be a bug in [language-javascript](https://github.com/atom/language-javascript) (although I'm not sure if language packages can specify things that cause newlines).

`linter-eslint` *could* resolve the issue by doing a conversion from "javascript lines" to "atom lines", and updating the location from ESLint appropriately. However, that solution might be a bit messy.

**Comment by skylize** [comment]
@not-an-aardvark If I understand your comments correctly, the _best_ place to fix this issue would be in `language-javascript`. Is that correct?

I cannot find any sign of anybody bothering to file an issue about this over there.

**Comment by not-an-aardvark** [comment]
I don't know a lot about atom internals, so it's hard for me to say. If `language-javascript` has the ability to specify what types of characters are considered to be linebreaks, then yes, this should be fixed in `language-javascript`. However, it might be the case that atom doesn't allow customizable linebreaks at all, in which case `linter-eslint` would probably have to do a conversion so that it can transform the errors appropriately.

**Comment by Arcanemagus** [comment]
Filed a bug on `tree-sitter-javascript` to bring this up again over there.
