### ISSUE TITLE
Rules dir should be optional

### ISSUE THREAD

**Issue by trodrigues** [AtomLinter/linter-eslint#759]
## Issue Type
Feature Request

## Issue Description
I've been working on a project which uses some extra rules defined in a directory as part of the code. If I want Atom to pick them up, I need to set the path to that directory in the plugin.

However, when I work in other projects the plugin does nothing because it doesn't find that directory.

It would be nice to have that being optional, so if it's not detected it just ignores it.

**Comment by IanVS** [comment]
This seems reasonable.  Is it something you're willing to work on and submit a PR for?  It likely won't have high priority from the rest of the `linter-eslint` team.

**Comment by xdissent** [comment]
If you're using the `--rulesdir` cli arg, it's been half-deprecated since eslint 1.x, and there's not really a way to inform an IDE of the path, since there's no equivalent `.eslintrc` option. Eslint suggests you create a plugin for your custom rules, but it *must* have the `eslint-plugin-` prefix *and* be installable via `npm`, which is impractical for local, private rules. An easy way to satisfy those requirements without publishing to npm is to add a `package.json` to your rules folder inside your project, and add `"eslint-plugin-my-rules": "file:path/to/my-rules"` to your project's `package.json`. That's what React does: https://github.com/facebook/react/commit/30cce21ae6c4e960ea629908fc8c307e41e2bae8 You'll have to prefix your rule names with `my-rules/`, but it should otherwise operate the same as `--rulesdir`.

**Comment by fcFn** [comment]
It could at least display some kind of warning that the custom rules directory wasn't found, not just silently stop working.

**Comment by fcFn** [comment]
I made a PR. It simply drops the `rulesDir` argument to ESLint if the custom rules directory could not be find.
