### ISSUE TITLE
glob pattern not ignoring import/no-extraneous-dependencies errors

### ISSUE THREAD

**Issue by drewlandis** [AtomLinter/linter-eslint#771]
## Issue Type
Bug

## Issue Description
I'm using the airbnb style guide which should cause eslint to ignore the `import/no-extraneous-dependencies` error in certain file paths.  See [here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L70). However, the eslint atom plugin still throws the error. When calling eslint from the CLI, no error is thrown.

I created a test repo [here](https://github.com/drewlandis/eslint-atom-extraneous-dependency-error) that demonstrates the issue.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
atom version: 1.12.7
linter-eslint version: 8.0.0
eslint version: 3.12.2
hours since last atom restart: 0
platform: darwin
Using local project eslint from /learning/eslint-atom-extraneous-dependency-error/node_modules/eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by RipTheJacker** [comment]
+1. but I also have this issue when using a .eslintrc file within another folder. If I use this rule in the main .eslintrc, the error is correctly ignored, in a subfolder, the error doesn't show up in the list but still shows up with red underline in my code (and as an error for the whole line).

**Comment by RipTheJacker** [comment]
+1

**Comment by IanVS** [comment]
Thanks for the example repo and complete issue report, @drewlandis.  That was very helpful. 

I believe I've determined what is happening.

The relevant part of the config you linked to above is:

```js
    // paths are treated both as absolute paths, and relative to process.cwd()
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: [
        'test/**', // tape, common npm pattern
```

As you can see, this only works if `cwd` is set to the project root.  However, when you open a file or project in Atom, the `cwd` is normally the file itself.  So, the glob for `test/**` does not match.

One way to force `linter-eslint` to set `cwd` to your project root is to add an `.eslintignore` file to your root folder (the file can be empty).  That is because we have some logic to look for such files and change the working directory to its folder if we find one (see https://github.com/AtomLinter/linter-eslint/issues/610#issuecomment-270277294 for more details).  I verified in your test repo that adding an empty `.eslintignore` file does work.  

If that's not a good solution for you, I would suggest adding an eslint config file in your `tests/` directory to allow devDependencies there.

Unfortunately there's nothing we can change in `linter-eslint` to fix the `cwd` issue.  I'm going to close this issue, but feel free to keep discussing.

**Comment by drewlandis** [comment]
Awesome, that works for me. Thanks for the solution! 👍

**Comment by renanol** [comment]
@IanVS Why can you change in linter-eslint to fix the cwd issue?

**Comment by IanVS** [comment]
I'm open to ideas of how to do that, but I haven't found one yet, aside from finding an `.eslintignore` file and setting cwd to that directory.  Do you have a suggestion, @renanol?

**Comment by renanol** [comment]
I thought there was some problem that would prevent for fix this issue. But I'll try to find a better solution, that don't need to create an `.eslintignore` .

Thank you!

**Comment by IanVS** [comment]
The main problem is that there is no _reliable_ method of determining the "root" of a project within a text editor like Atom.  When you run eslint via the command line, you usually run it from the project root, and that sets the CWD correctly.  By contrast, files can be opened individually in Atom, and in that case, how should we find the project root?  ESLint config files can be scattered throughout a project, not every file is an npm module with a `package.json` (and those can be sprinkled throughout as well), `.gitignore` files cascade and are not in every project, etc.

**Comment by renanol** [comment]
I understood. Thank for your explanation.
