### ISSUE TITLE
eslint-atom still lints when no .eslintrc file is present in project

### ISSUE THREAD

**Issue by joeelectricity** [AtomLinter/linter-eslint#785]
## Issue Type
Bug

## Issue Description
http://i.imgur.com/rPT5eX5.png
Despite the above settings (no default rule file, and set not to lint when no config file is present), linter-eslint still runs on files in a project with no .eslintrc file present.

**Comment by IanVS** [comment]
Do you have any eslint config between your project and the root directory?

**Comment by joeelectricity** [comment]
> Do you have any eslint config between your project and the root directory?
That was the issue... Sorry about that.

Why, out of curiosity, does the plugin search outside of my project directory? I'd understand anything within the project directory but it seems strange to include in the other direction.

**Comment by IanVS** [comment]
>Why, out of curiosity, does the plugin search outside of my project directory?

It's because this library is just a simple plugin to allow you to run ESLint, and that's how ESLint works.  You can read more about [ESLint configuration cascading](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) if you want the details.  There _is_ one small bug in `linter-eslint` that will cause it to work slightly differently from the ESLint CLI in your case, the PR to fix it is https://github.com/AtomLinter/linter-eslint/pull/778.
