### ISSUE TITLE
Feature request: Add support for .eslintrc config files with extensions (.js, .json, .yaml/.yml)

### ISSUE THREAD

**Issue by zbrownell** [AtomLinter/linter-eslint#808]
## Issue Type
Feature Request

## Issue Description
The linter-eslint (v8.1.0) package in Atom does not seem to recognize .eslintrc config files that possess file types (e.g. - .eslintrc.js). Since the default setting is to "Disable when no ESLint config is found (in package.json or .eslintrc)", the end result is that no eslint checks are performed in the IDE and a manual run on the command line is required to get at formatting/syntax errors.

Since the .eslintrc config file seems to have been deprecated (see: http://eslint.org/docs/user-guide/configuring#configuration-file-formats), it seems like this package should support the current format.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```
Running the `Linter Eslint: Debug` command from the Command Palette shows that the eslint rules found are from a sibling `node_modules` folder of the code in question's ancestors (go up a few folders and grab settings from sibling at this level), instead of reading in rules from two nested, direct ancestor .eslintrc.js files (that should be taking precedence).

I am unable to post file/folder hierarchies to this issue (apologies).

**Comment by IanVS** [comment]
Unfortunately, without a reproducible folder structure, we're not going to be able to investigate this. In general, `linter-eslint` supports the extensions you mentioned. Can you create a repo which exhibits the problem you're seeing?

**Comment by gluons** [comment]
Same here.
I enabled `Disable when no ESLint config is found (in package.json or .eslintrc)`.
I already have [`.eslintrc.*`](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) file in top of project folder.
But `linter-eslint` doesn't lint any file in my project.

After I disable `Disable when no ESLint config is found (in package.json or .eslintrc)`, it work. 😕 

`linter-eslint` can't detect [`.eslintrc.*`](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) file.

**To reproduce:** Just create project with [`.eslintrc.*`](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) config file and type some code.

**Comment by Arcanemagus** [comment]
Without an example folder structure, or at the very least the output of the debug command it's impossible for us to look into this because it works just fine as far as we can see.

**Comment by michaeljdennis** [comment]
I am seeing the same behavior as described above.

Mac OS 10.12.3
Atom 1.15.0
-linter 2.1.0
-linter-eslint 8.1.4
Node v7.7.3
NPM 4.1.2

Folder structure:
./.eslintrc.js
./app.js

When I use .eslintrc everything works as expected. When I use .eslintrc.js I receive an error:
"[Linter] Error running ESLint"

Console error:
[Linter] Error running ESLint Error: Cannot read config file: /Users/michael/sites/eslint-test/.eslintrc.js(…) linter-registry.js [sm]:144 
(anonymous function)	@	linter-registry.js [sm]:144

Please let me know if you need any further info to help debug. Thanks!

**Comment by Arcanemagus** [comment]
@michaeljdennis Same thing that has been said to the others in this thread, can you post the output of the debug command? 😛

Also, check the permissions on `/Users/michael/sites/eslint-test/.eslintrc.js` as it looks like it might have found a configuration, but for some reason is unable to read the file?

**Comment by michaeljdennis** [comment]
@Arcanemagus 
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.18.0
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/michael/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "punctuation.definition.function.body.begin.bracket.curly.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}

**Comment by Arcanemagus** [comment]
@michaeljdennis Pinged you on Atom's Slack.

Anyone else that is experiencing this and would like to try to track this down feel free to contact me on [Atom's Slack](http://atom-slack.herokuapp.com/) as unfortunately the error makes no sense from the information posted so far 😕.

**Comment by Arcanemagus** [comment]
@michaeljdennis While attempting to reproduce a different bug I ran into what you describe here. It turns out that this is probably a mistake in converting a `.eslintrc` file straight to a `.eslintrc.js` file and forgetting to properly quote one of the rule names. In the case I was working on `no-undef` was unquoted which lead to invalid javascript. And instead of a nice sensible error, ESLint gives back "Unable to read the file".

**Comment by michaeljdennis** [comment]
@Arcanemagus Good catch. It should throw a more informative error than that. Here's the .eslintrc.js file that's currently failing for me: https://gist.github.com/michaeljdennis/991f4a2aa7a1e5b28259e25d9e6aea42

**Comment by Arcanemagus** [comment]
Yours is missing the `module.exports = ` at the start 😉. You can find a basic example [here](https://github.com/eslint/eslint/blob/v3.19.0/tests/fixtures/config-file/js/.eslintrc.js).

**Comment by michaeljdennis** [comment]
@Arcanemagus It works! Thanks for keeping this issue updated!
