### ISSUE TITLE
option to silence all fixable rules while typing

### ISSUE THREAD

**Issue by robjtede** [AtomLinter/linter-eslint#894]
## Issue Type

Feature Request

## Issue Description

The silence specific rules while typing option is amazing but difficult to keep up to date with .eslintrc changes and, especially, to synchronise between team members.
If eslint exposes a list of "fixable" rules (or otherwise), can a checkbox that enable all the fixable rules to be silenced and just fixed on save?

**Comment by jaydenseric** [comment]
Brilliant idea! It could be smart, and only silence the fixable errors if fix on save is enabled.

**Comment by jaydenseric** [comment]
Brilliant idea! It could be smart, and only silence the fixable errors if fix on save is enabled.

**Comment by IanVS** [comment]
This is a nice idea, although it may be tricky to implement.  ESLint rules contain metadata, including whether or not they are fixable, but that metadata is include with the rules themselves, and is not in the reports that ESLint provides for each error.  Additionally, just because a rule says it is fixable, does not necessarily mean that the fixes will be successful each time, only that ESLint will _attempt_ to make a fix.  

I'm going to keep this issue open to see what others think.  I don't think this will be a priority for the project maintainers, but if someone else wants to try to implement this, feel free.

**Comment by robjtede** [comment]
🎉🎉

**Comment by nfarina** [comment]
I absolutely *love* this feature! I can't seem to make it work though - when I introduce errors like "trailing spaces" into my unsaved JS file, I still get ESLint errors even with this feature enabled. These errors are then fixed on save.

<img width="550" alt="screen shot 2017-10-19 at 11 32 35 am" src="https://user-images.githubusercontent.com/117280/31787706-722db4a6-b4c1-11e7-8847-b6950dd35006.png">

Any idea what I'm doing wrong? This is happening with both the `linter` package and the newer `atom-ide-ui` conglomerate.

**Comment by nfarina** [comment]
Well it just started working. I tried adding a rule to "silence specific rules while typing" then enabled the "ignore fixable rules" and everything started working - but I can't find anywhere in the code that would point to these actions having any effect. I'll keep trying to repro :)

**Comment by Arcanemagus** [comment]
@nfarina Note that you _must_ run a regular lint job first to populate the list of rules to ignore from ESLint.

**Comment by nfarina** [comment]
@Arcanemagus That is helpful - how do I do that from within Atom? It seems like it's all managed in the background. Is that triggered when saving a file?

**Comment by Arcanemagus** [comment]
Assuming you are using `linter` it will be triggered on saving the file always, on editing if you have `Lint on Change` enabled, and manually on running `Linter: Lint`.

I haven't dug into when exactly `atom-ide-ui` triggers a lint but it _seems_ to be on save and on changes.
