### ISSUE TITLE
linter-eslint blows up in Atom with "Cannot read property 'createElement' of undefined" with eslint-plugin-piggyback

### ISSUE THREAD

**Issue by joshclow** [AtomLinter/linter-eslint#944]
## Issue Type

Bug

## Issue Description

1) Atom with linter and linter-eslint as the only community Packages
2) a fresh npm init project with eslint and eslint-plugin-piggyback as the only devDependencies (and no other dependencies defined)
3) an .eslintrc containing only the plugins entry to enable the plugin
4) a trivial js file

opening this project in Atom crashes linter-eslint, while eslint at the cli does not.
Crash appears to be when the plugin attempts to initialize jQuery as it is spinning up.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.18.0
linter-eslint version: 8.2.1
ESLint version: 4.0.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/textio/Repos/test/node_modules/eslint
Current file's scopes: [
  "source.js"
]
linter-eslint configuration: {
  "fixOnSave": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Hmmm, I'm more confused as to how this is working in the CLI, as it really _shouldn't_ be. I've seen other cases where ESLint silently "eats" errors and I'm guessing that is why it "works" in the CLI for you.

jQuery is designed in an... _interesting_ way and makes far too many assumptions about being ran in a browser. In this case the issue is that it assumes `document` is a global variable, which it definitely isn't in Node.js.

I managed to get this to not throw errors at least by changing the way that `eslint-plugin-piggyback` loads jQuery. I changed [these lines](https://github.com/cowchimp/eslint-plugin-piggyback/blob/382eca12f1e37f6b59098ac06ed15d125eaf76c1/lib/rules/no-jquery-extend.js#L13-L17) to:

```js
var jsdom = require('jsdom');
window = jsdom.jsdom().defaultView;
var jQuery = require('jquery');
var $ = jQuery(window);
```

`window` needs to be in the global scope _before_ jQuery even gets `require`ed, and yes the dropping of `var` from it was intentional.

You may want to file an issue on that repo about this, it's an extremely ugly hack though.

Marking this issue as closed since it isn't a bug here.
